// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/keypad_conditions_to_lamp_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateKeypadConditionToLampEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InteractionID string `protobuf:"bytes,1,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,2,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,3,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *CreateKeypadConditionToLampEventRequest) Reset() {
	*x = CreateKeypadConditionToLampEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKeypadConditionToLampEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeypadConditionToLampEventRequest) ProtoMessage() {}

func (x *CreateKeypadConditionToLampEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeypadConditionToLampEventRequest.ProtoReflect.Descriptor instead.
func (*CreateKeypadConditionToLampEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateKeypadConditionToLampEventRequest) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *CreateKeypadConditionToLampEventRequest) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *CreateKeypadConditionToLampEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type CreateKeypadConditionToLampEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *CreateKeypadConditionToLampEventResponse) Reset() {
	*x = CreateKeypadConditionToLampEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKeypadConditionToLampEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeypadConditionToLampEventResponse) ProtoMessage() {}

func (x *CreateKeypadConditionToLampEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeypadConditionToLampEventResponse.ProtoReflect.Descriptor instead.
func (*CreateKeypadConditionToLampEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKeypadConditionToLampEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateKeypadConditionToLampEventResponse) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *CreateKeypadConditionToLampEventResponse) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *CreateKeypadConditionToLampEventResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type GetKeypadConditionToLampEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetKeypadConditionToLampEventRequest) Reset() {
	*x = GetKeypadConditionToLampEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeypadConditionToLampEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeypadConditionToLampEventRequest) ProtoMessage() {}

func (x *GetKeypadConditionToLampEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeypadConditionToLampEventRequest.ProtoReflect.Descriptor instead.
func (*GetKeypadConditionToLampEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeypadConditionToLampEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetKeypadConditionToLampEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *GetKeypadConditionToLampEventResponse) Reset() {
	*x = GetKeypadConditionToLampEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeypadConditionToLampEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeypadConditionToLampEventResponse) ProtoMessage() {}

func (x *GetKeypadConditionToLampEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeypadConditionToLampEventResponse.ProtoReflect.Descriptor instead.
func (*GetKeypadConditionToLampEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeypadConditionToLampEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetKeypadConditionToLampEventResponse) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *GetKeypadConditionToLampEventResponse) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *GetKeypadConditionToLampEventResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type UpdateKeypadConditionToLampEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *UpdateKeypadConditionToLampEventRequest) Reset() {
	*x = UpdateKeypadConditionToLampEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKeypadConditionToLampEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeypadConditionToLampEventRequest) ProtoMessage() {}

func (x *UpdateKeypadConditionToLampEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeypadConditionToLampEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeypadConditionToLampEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateKeypadConditionToLampEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateKeypadConditionToLampEventRequest) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *UpdateKeypadConditionToLampEventRequest) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *UpdateKeypadConditionToLampEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type UpdateKeypadConditionToLampEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *UpdateKeypadConditionToLampEventResponse) Reset() {
	*x = UpdateKeypadConditionToLampEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKeypadConditionToLampEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeypadConditionToLampEventResponse) ProtoMessage() {}

func (x *UpdateKeypadConditionToLampEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeypadConditionToLampEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateKeypadConditionToLampEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateKeypadConditionToLampEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateKeypadConditionToLampEventResponse) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *UpdateKeypadConditionToLampEventResponse) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *UpdateKeypadConditionToLampEventResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type DeleteKeypadConditionToLampEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteKeypadConditionToLampEventRequest) Reset() {
	*x = DeleteKeypadConditionToLampEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeypadConditionToLampEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeypadConditionToLampEventRequest) ProtoMessage() {}

func (x *DeleteKeypadConditionToLampEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeypadConditionToLampEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeypadConditionToLampEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKeypadConditionToLampEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteKeypadConditionToLampEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteKeypadConditionToLampEventResponse) Reset() {
	*x = DeleteKeypadConditionToLampEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeypadConditionToLampEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeypadConditionToLampEventResponse) ProtoMessage() {}

func (x *DeleteKeypadConditionToLampEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeypadConditionToLampEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeypadConditionToLampEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKeypadConditionToLampEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_keypad_conditions_to_lamp_events_messages_proto protoreflect.FileDescriptor

var file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDesc = []byte{
	0x0a, 0x38, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6b, 0x65, 0x79, 0x70, 0x61,
	0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x74, 0x6f, 0x5f,
	0x6c, 0x61, 0x6d, 0x70, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x8b, 0x01, 0x0a, 0x27,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x4c, 0x61, 0x6d, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x9c, 0x01, 0x0a, 0x28, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x4c, 0x61, 0x6d, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x36, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x4b,
	0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f,
	0x4c, 0x61, 0x6d, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x99, 0x01, 0x0a, 0x25, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x4c, 0x61, 0x6d, 0x70, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x9b, 0x01, 0x0a,
	0x27, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x4c, 0x61, 0x6d, 0x70, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x9c, 0x01, 0x0a, 0x28, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x4c, 0x61, 0x6d, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x27, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x6f, 0x4c, 0x61, 0x6d, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x28, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x4c,
	0x61, 0x6d, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescOnce sync.Once
	file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescData = file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDesc
)

func file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescGZIP() []byte {
	file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescData)
	})
	return file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDescData
}

var file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_keypad_conditions_to_lamp_events_messages_proto_goTypes = []interface{}{
	(*CreateKeypadConditionToLampEventRequest)(nil),  // 0: interactions_pb.CreateKeypadConditionToLampEventRequest
	(*CreateKeypadConditionToLampEventResponse)(nil), // 1: interactions_pb.CreateKeypadConditionToLampEventResponse
	(*GetKeypadConditionToLampEventRequest)(nil),     // 2: interactions_pb.GetKeypadConditionToLampEventRequest
	(*GetKeypadConditionToLampEventResponse)(nil),    // 3: interactions_pb.GetKeypadConditionToLampEventResponse
	(*UpdateKeypadConditionToLampEventRequest)(nil),  // 4: interactions_pb.UpdateKeypadConditionToLampEventRequest
	(*UpdateKeypadConditionToLampEventResponse)(nil), // 5: interactions_pb.UpdateKeypadConditionToLampEventResponse
	(*DeleteKeypadConditionToLampEventRequest)(nil),  // 6: interactions_pb.DeleteKeypadConditionToLampEventRequest
	(*DeleteKeypadConditionToLampEventResponse)(nil), // 7: interactions_pb.DeleteKeypadConditionToLampEventResponse
}
var file_messages_keypad_conditions_to_lamp_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_keypad_conditions_to_lamp_events_messages_proto_init() }
func file_messages_keypad_conditions_to_lamp_events_messages_proto_init() {
	if File_messages_keypad_conditions_to_lamp_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKeypadConditionToLampEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKeypadConditionToLampEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeypadConditionToLampEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeypadConditionToLampEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKeypadConditionToLampEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKeypadConditionToLampEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeypadConditionToLampEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeypadConditionToLampEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_keypad_conditions_to_lamp_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_keypad_conditions_to_lamp_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_keypad_conditions_to_lamp_events_messages_proto_msgTypes,
	}.Build()
	File_messages_keypad_conditions_to_lamp_events_messages_proto = out.File
	file_messages_keypad_conditions_to_lamp_events_messages_proto_rawDesc = nil
	file_messages_keypad_conditions_to_lamp_events_messages_proto_goTypes = nil
	file_messages_keypad_conditions_to_lamp_events_messages_proto_depIdxs = nil
}
