// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/lamp_auto_brightness_on_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateLampAutoBrightnessOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampAutoBrightnessOnEventRequest) Reset() {
	*x = CreateLampAutoBrightnessOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampAutoBrightnessOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampAutoBrightnessOnEventRequest) ProtoMessage() {}

func (x *CreateLampAutoBrightnessOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampAutoBrightnessOnEventRequest.ProtoReflect.Descriptor instead.
func (*CreateLampAutoBrightnessOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLampAutoBrightnessOnEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type CreateLampAutoBrightnessOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampAutoBrightnessOnEventResponse) Reset() {
	*x = CreateLampAutoBrightnessOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampAutoBrightnessOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampAutoBrightnessOnEventResponse) ProtoMessage() {}

func (x *CreateLampAutoBrightnessOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampAutoBrightnessOnEventResponse.ProtoReflect.Descriptor instead.
func (*CreateLampAutoBrightnessOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLampAutoBrightnessOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLampAutoBrightnessOnEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type GetLampAutoBrightnessOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetLampAutoBrightnessOnEventRequest) Reset() {
	*x = GetLampAutoBrightnessOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampAutoBrightnessOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampAutoBrightnessOnEventRequest) ProtoMessage() {}

func (x *GetLampAutoBrightnessOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampAutoBrightnessOnEventRequest.ProtoReflect.Descriptor instead.
func (*GetLampAutoBrightnessOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetLampAutoBrightnessOnEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLampAutoBrightnessOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *GetLampAutoBrightnessOnEventResponse) Reset() {
	*x = GetLampAutoBrightnessOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampAutoBrightnessOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampAutoBrightnessOnEventResponse) ProtoMessage() {}

func (x *GetLampAutoBrightnessOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampAutoBrightnessOnEventResponse.ProtoReflect.Descriptor instead.
func (*GetLampAutoBrightnessOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetLampAutoBrightnessOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetLampAutoBrightnessOnEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampAutoBrightnessOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampAutoBrightnessOnEventRequest) Reset() {
	*x = UpdateLampAutoBrightnessOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampAutoBrightnessOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampAutoBrightnessOnEventRequest) ProtoMessage() {}

func (x *UpdateLampAutoBrightnessOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampAutoBrightnessOnEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateLampAutoBrightnessOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLampAutoBrightnessOnEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampAutoBrightnessOnEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampAutoBrightnessOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampAutoBrightnessOnEventResponse) Reset() {
	*x = UpdateLampAutoBrightnessOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampAutoBrightnessOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampAutoBrightnessOnEventResponse) ProtoMessage() {}

func (x *UpdateLampAutoBrightnessOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampAutoBrightnessOnEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateLampAutoBrightnessOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLampAutoBrightnessOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampAutoBrightnessOnEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type DeleteLampAutoBrightnessOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampAutoBrightnessOnEventRequest) Reset() {
	*x = DeleteLampAutoBrightnessOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampAutoBrightnessOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampAutoBrightnessOnEventRequest) ProtoMessage() {}

func (x *DeleteLampAutoBrightnessOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampAutoBrightnessOnEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteLampAutoBrightnessOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLampAutoBrightnessOnEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLampAutoBrightnessOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampAutoBrightnessOnEventResponse) Reset() {
	*x = DeleteLampAutoBrightnessOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampAutoBrightnessOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampAutoBrightnessOnEventResponse) ProtoMessage() {}

func (x *DeleteLampAutoBrightnessOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampAutoBrightnessOnEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteLampAutoBrightnessOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLampAutoBrightnessOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_lamp_auto_brightness_on_events_messages_proto protoreflect.FileDescriptor

var file_messages_lamp_auto_brightness_on_events_messages_proto_rawDesc = []byte{
	0x0a, 0x36, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x5f,
	0x61, 0x75, 0x74, 0x6f, 0x5f, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x5f,
	0x6f, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x3a, 0x0a, 0x26, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x4b, 0x0a, 0x27, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73,
	0x73, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x61, 0x63, 0x22, 0x35, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74,
	0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x48, 0x0a, 0x24, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x61, 0x63, 0x22, 0x4a, 0x0a, 0x26, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d,
	0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f,
	0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22,
	0x4b, 0x0a, 0x27, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74,
	0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x38, 0x0a, 0x26,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x27, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescOnce sync.Once
	file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescData = file_messages_lamp_auto_brightness_on_events_messages_proto_rawDesc
)

func file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescGZIP() []byte {
	file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescData)
	})
	return file_messages_lamp_auto_brightness_on_events_messages_proto_rawDescData
}

var file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_lamp_auto_brightness_on_events_messages_proto_goTypes = []interface{}{
	(*CreateLampAutoBrightnessOnEventRequest)(nil),  // 0: interactions_pb.CreateLampAutoBrightnessOnEventRequest
	(*CreateLampAutoBrightnessOnEventResponse)(nil), // 1: interactions_pb.CreateLampAutoBrightnessOnEventResponse
	(*GetLampAutoBrightnessOnEventRequest)(nil),     // 2: interactions_pb.GetLampAutoBrightnessOnEventRequest
	(*GetLampAutoBrightnessOnEventResponse)(nil),    // 3: interactions_pb.GetLampAutoBrightnessOnEventResponse
	(*UpdateLampAutoBrightnessOnEventRequest)(nil),  // 4: interactions_pb.UpdateLampAutoBrightnessOnEventRequest
	(*UpdateLampAutoBrightnessOnEventResponse)(nil), // 5: interactions_pb.UpdateLampAutoBrightnessOnEventResponse
	(*DeleteLampAutoBrightnessOnEventRequest)(nil),  // 6: interactions_pb.DeleteLampAutoBrightnessOnEventRequest
	(*DeleteLampAutoBrightnessOnEventResponse)(nil), // 7: interactions_pb.DeleteLampAutoBrightnessOnEventResponse
}
var file_messages_lamp_auto_brightness_on_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_lamp_auto_brightness_on_events_messages_proto_init() }
func file_messages_lamp_auto_brightness_on_events_messages_proto_init() {
	if File_messages_lamp_auto_brightness_on_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampAutoBrightnessOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampAutoBrightnessOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampAutoBrightnessOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampAutoBrightnessOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampAutoBrightnessOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampAutoBrightnessOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampAutoBrightnessOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampAutoBrightnessOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_lamp_auto_brightness_on_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_lamp_auto_brightness_on_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_lamp_auto_brightness_on_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_lamp_auto_brightness_on_events_messages_proto_msgTypes,
	}.Build()
	File_messages_lamp_auto_brightness_on_events_messages_proto = out.File
	file_messages_lamp_auto_brightness_on_events_messages_proto_rawDesc = nil
	file_messages_lamp_auto_brightness_on_events_messages_proto_goTypes = nil
	file_messages_lamp_auto_brightness_on_events_messages_proto_depIdxs = nil
}
