// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/lamp_on_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateLampOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampOnEventRequest) Reset() {
	*x = CreateLampOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampOnEventRequest) ProtoMessage() {}

func (x *CreateLampOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampOnEventRequest.ProtoReflect.Descriptor instead.
func (*CreateLampOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLampOnEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type CreateLampOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampOnEventResponse) Reset() {
	*x = CreateLampOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampOnEventResponse) ProtoMessage() {}

func (x *CreateLampOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampOnEventResponse.ProtoReflect.Descriptor instead.
func (*CreateLampOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLampOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLampOnEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type GetLampOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetLampOnEventRequest) Reset() {
	*x = GetLampOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampOnEventRequest) ProtoMessage() {}

func (x *GetLampOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampOnEventRequest.ProtoReflect.Descriptor instead.
func (*GetLampOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetLampOnEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLampOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *GetLampOnEventResponse) Reset() {
	*x = GetLampOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampOnEventResponse) ProtoMessage() {}

func (x *GetLampOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampOnEventResponse.ProtoReflect.Descriptor instead.
func (*GetLampOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetLampOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetLampOnEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampOnEventRequest) Reset() {
	*x = UpdateLampOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampOnEventRequest) ProtoMessage() {}

func (x *UpdateLampOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampOnEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateLampOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLampOnEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampOnEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampOnEventResponse) Reset() {
	*x = UpdateLampOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampOnEventResponse) ProtoMessage() {}

func (x *UpdateLampOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampOnEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateLampOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLampOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampOnEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type DeleteLampOnEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampOnEventRequest) Reset() {
	*x = DeleteLampOnEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampOnEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampOnEventRequest) ProtoMessage() {}

func (x *DeleteLampOnEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampOnEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteLampOnEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLampOnEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLampOnEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampOnEventResponse) Reset() {
	*x = DeleteLampOnEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_on_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampOnEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampOnEventResponse) ProtoMessage() {}

func (x *DeleteLampOnEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_on_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampOnEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteLampOnEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_on_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLampOnEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_lamp_on_events_messages_proto protoreflect.FileDescriptor

var file_messages_lamp_on_events_messages_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x5f,
	0x6f, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x2c, 0x0a, 0x18, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x3d, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d,
	0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x3a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x3c, 0x0a, 0x18, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x3d, 0x0a, 0x19, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61,
	0x6d, 0x70, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_lamp_on_events_messages_proto_rawDescOnce sync.Once
	file_messages_lamp_on_events_messages_proto_rawDescData = file_messages_lamp_on_events_messages_proto_rawDesc
)

func file_messages_lamp_on_events_messages_proto_rawDescGZIP() []byte {
	file_messages_lamp_on_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_lamp_on_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_lamp_on_events_messages_proto_rawDescData)
	})
	return file_messages_lamp_on_events_messages_proto_rawDescData
}

var file_messages_lamp_on_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_lamp_on_events_messages_proto_goTypes = []interface{}{
	(*CreateLampOnEventRequest)(nil),  // 0: interactions_pb.CreateLampOnEventRequest
	(*CreateLampOnEventResponse)(nil), // 1: interactions_pb.CreateLampOnEventResponse
	(*GetLampOnEventRequest)(nil),     // 2: interactions_pb.GetLampOnEventRequest
	(*GetLampOnEventResponse)(nil),    // 3: interactions_pb.GetLampOnEventResponse
	(*UpdateLampOnEventRequest)(nil),  // 4: interactions_pb.UpdateLampOnEventRequest
	(*UpdateLampOnEventResponse)(nil), // 5: interactions_pb.UpdateLampOnEventResponse
	(*DeleteLampOnEventRequest)(nil),  // 6: interactions_pb.DeleteLampOnEventRequest
	(*DeleteLampOnEventResponse)(nil), // 7: interactions_pb.DeleteLampOnEventResponse
}
var file_messages_lamp_on_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_lamp_on_events_messages_proto_init() }
func file_messages_lamp_on_events_messages_proto_init() {
	if File_messages_lamp_on_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_lamp_on_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_on_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_on_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_on_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_on_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_on_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_on_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampOnEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_on_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampOnEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_lamp_on_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_lamp_on_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_lamp_on_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_lamp_on_events_messages_proto_msgTypes,
	}.Build()
	File_messages_lamp_on_events_messages_proto = out.File
	file_messages_lamp_on_events_messages_proto_rawDesc = nil
	file_messages_lamp_on_events_messages_proto_goTypes = nil
	file_messages_lamp_on_events_messages_proto_depIdxs = nil
}
