// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/lamp_toggle_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateLampToggleEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampToggleEventRequest) Reset() {
	*x = CreateLampToggleEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampToggleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampToggleEventRequest) ProtoMessage() {}

func (x *CreateLampToggleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampToggleEventRequest.ProtoReflect.Descriptor instead.
func (*CreateLampToggleEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLampToggleEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type CreateLampToggleEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampToggleEventResponse) Reset() {
	*x = CreateLampToggleEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampToggleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampToggleEventResponse) ProtoMessage() {}

func (x *CreateLampToggleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampToggleEventResponse.ProtoReflect.Descriptor instead.
func (*CreateLampToggleEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLampToggleEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLampToggleEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type GetLampToggleEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetLampToggleEventRequest) Reset() {
	*x = GetLampToggleEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampToggleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampToggleEventRequest) ProtoMessage() {}

func (x *GetLampToggleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampToggleEventRequest.ProtoReflect.Descriptor instead.
func (*GetLampToggleEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetLampToggleEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLampToggleEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *GetLampToggleEventResponse) Reset() {
	*x = GetLampToggleEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampToggleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampToggleEventResponse) ProtoMessage() {}

func (x *GetLampToggleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampToggleEventResponse.ProtoReflect.Descriptor instead.
func (*GetLampToggleEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetLampToggleEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetLampToggleEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampToggleEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampToggleEventRequest) Reset() {
	*x = UpdateLampToggleEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampToggleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampToggleEventRequest) ProtoMessage() {}

func (x *UpdateLampToggleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampToggleEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateLampToggleEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLampToggleEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampToggleEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampToggleEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampToggleEventResponse) Reset() {
	*x = UpdateLampToggleEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampToggleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampToggleEventResponse) ProtoMessage() {}

func (x *UpdateLampToggleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampToggleEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateLampToggleEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLampToggleEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampToggleEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type DeleteLampToggleEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampToggleEventRequest) Reset() {
	*x = DeleteLampToggleEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampToggleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampToggleEventRequest) ProtoMessage() {}

func (x *DeleteLampToggleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampToggleEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteLampToggleEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLampToggleEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLampToggleEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampToggleEventResponse) Reset() {
	*x = DeleteLampToggleEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampToggleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampToggleEventResponse) ProtoMessage() {}

func (x *DeleteLampToggleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_toggle_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampToggleEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteLampToggleEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_toggle_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLampToggleEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_lamp_toggle_events_messages_proto protoreflect.FileDescriptor

var file_messages_lamp_toggle_events_messages_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x5f,
	0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x30, 0x0a,
	0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x54, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22,
	0x41, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x61, 0x63, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x3e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22,
	0x40, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61,
	0x63, 0x22, 0x41, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x61, 0x63, 0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61,
	0x6d, 0x70, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x2f, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61,
	0x6d, 0x70, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_messages_lamp_toggle_events_messages_proto_rawDescOnce sync.Once
	file_messages_lamp_toggle_events_messages_proto_rawDescData = file_messages_lamp_toggle_events_messages_proto_rawDesc
)

func file_messages_lamp_toggle_events_messages_proto_rawDescGZIP() []byte {
	file_messages_lamp_toggle_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_lamp_toggle_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_lamp_toggle_events_messages_proto_rawDescData)
	})
	return file_messages_lamp_toggle_events_messages_proto_rawDescData
}

var file_messages_lamp_toggle_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_lamp_toggle_events_messages_proto_goTypes = []interface{}{
	(*CreateLampToggleEventRequest)(nil),  // 0: interactions_pb.CreateLampToggleEventRequest
	(*CreateLampToggleEventResponse)(nil), // 1: interactions_pb.CreateLampToggleEventResponse
	(*GetLampToggleEventRequest)(nil),     // 2: interactions_pb.GetLampToggleEventRequest
	(*GetLampToggleEventResponse)(nil),    // 3: interactions_pb.GetLampToggleEventResponse
	(*UpdateLampToggleEventRequest)(nil),  // 4: interactions_pb.UpdateLampToggleEventRequest
	(*UpdateLampToggleEventResponse)(nil), // 5: interactions_pb.UpdateLampToggleEventResponse
	(*DeleteLampToggleEventRequest)(nil),  // 6: interactions_pb.DeleteLampToggleEventRequest
	(*DeleteLampToggleEventResponse)(nil), // 7: interactions_pb.DeleteLampToggleEventResponse
}
var file_messages_lamp_toggle_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_lamp_toggle_events_messages_proto_init() }
func file_messages_lamp_toggle_events_messages_proto_init() {
	if File_messages_lamp_toggle_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_lamp_toggle_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampToggleEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_toggle_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampToggleEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_toggle_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampToggleEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_toggle_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampToggleEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_toggle_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampToggleEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_toggle_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampToggleEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_toggle_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampToggleEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_toggle_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampToggleEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_lamp_toggle_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_lamp_toggle_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_lamp_toggle_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_lamp_toggle_events_messages_proto_msgTypes,
	}.Build()
	File_messages_lamp_toggle_events_messages_proto = out.File
	file_messages_lamp_toggle_events_messages_proto_rawDesc = nil
	file_messages_lamp_toggle_events_messages_proto_goTypes = nil
	file_messages_lamp_toggle_events_messages_proto_depIdxs = nil
}
