// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package devices_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DevicesServiceClient is the client API for DevicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevicesServiceClient interface {
	CreateBatCaveDeviceSetting(ctx context.Context, in *CreateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*CreateBatCaveDeviceSettingResponse, error)
	GetBatCaveDeviceSetting(ctx context.Context, in *GetBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*GetBatCaveDeviceSettingResponse, error)
	UpdateBatCaveDeviceSetting(ctx context.Context, in *UpdateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*UpdateBatCaveDeviceSettingResponse, error)
	SendLampDeviceOn(ctx context.Context, in *SendLampDeviceOnRequest, opts ...grpc.CallOption) (*SendLampDeviceOnResponse, error)
	SendLampDeviceOff(ctx context.Context, in *SendLampDeviceOffRequest, opts ...grpc.CallOption) (*SendLampDeviceOffResponse, error)
	SendLampDeviceColor(ctx context.Context, in *SendLampDeviceColorRequest, opts ...grpc.CallOption) (*SendLampDeviceColorResponse, error)
	SendLampDeviceBrightness(ctx context.Context, in *SendLampDeviceBrightnessRequest, opts ...grpc.CallOption) (*SendLampDeviceBrightnessResponse, error)
	SendLampDevicePulse(ctx context.Context, in *SendLampDevicePulseRequest, opts ...grpc.CallOption) (*SendLampDevicePulseResponse, error)
}

type devicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevicesServiceClient(cc grpc.ClientConnInterface) DevicesServiceClient {
	return &devicesServiceClient{cc}
}

func (c *devicesServiceClient) CreateBatCaveDeviceSetting(ctx context.Context, in *CreateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*CreateBatCaveDeviceSettingResponse, error) {
	out := new(CreateBatCaveDeviceSettingResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/CreateBatCaveDeviceSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) GetBatCaveDeviceSetting(ctx context.Context, in *GetBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*GetBatCaveDeviceSettingResponse, error) {
	out := new(GetBatCaveDeviceSettingResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/GetBatCaveDeviceSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) UpdateBatCaveDeviceSetting(ctx context.Context, in *UpdateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*UpdateBatCaveDeviceSettingResponse, error) {
	out := new(UpdateBatCaveDeviceSettingResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/UpdateBatCaveDeviceSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) SendLampDeviceOn(ctx context.Context, in *SendLampDeviceOnRequest, opts ...grpc.CallOption) (*SendLampDeviceOnResponse, error) {
	out := new(SendLampDeviceOnResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/SendLampDeviceOn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) SendLampDeviceOff(ctx context.Context, in *SendLampDeviceOffRequest, opts ...grpc.CallOption) (*SendLampDeviceOffResponse, error) {
	out := new(SendLampDeviceOffResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/SendLampDeviceOff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) SendLampDeviceColor(ctx context.Context, in *SendLampDeviceColorRequest, opts ...grpc.CallOption) (*SendLampDeviceColorResponse, error) {
	out := new(SendLampDeviceColorResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/SendLampDeviceColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) SendLampDeviceBrightness(ctx context.Context, in *SendLampDeviceBrightnessRequest, opts ...grpc.CallOption) (*SendLampDeviceBrightnessResponse, error) {
	out := new(SendLampDeviceBrightnessResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/SendLampDeviceBrightness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) SendLampDevicePulse(ctx context.Context, in *SendLampDevicePulseRequest, opts ...grpc.CallOption) (*SendLampDevicePulseResponse, error) {
	out := new(SendLampDevicePulseResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/SendLampDevicePulse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServiceServer is the server API for DevicesService service.
// All implementations must embed UnimplementedDevicesServiceServer
// for forward compatibility
type DevicesServiceServer interface {
	CreateBatCaveDeviceSetting(context.Context, *CreateBatCaveDeviceSettingRequest) (*CreateBatCaveDeviceSettingResponse, error)
	GetBatCaveDeviceSetting(context.Context, *GetBatCaveDeviceSettingRequest) (*GetBatCaveDeviceSettingResponse, error)
	UpdateBatCaveDeviceSetting(context.Context, *UpdateBatCaveDeviceSettingRequest) (*UpdateBatCaveDeviceSettingResponse, error)
	SendLampDeviceOn(context.Context, *SendLampDeviceOnRequest) (*SendLampDeviceOnResponse, error)
	SendLampDeviceOff(context.Context, *SendLampDeviceOffRequest) (*SendLampDeviceOffResponse, error)
	SendLampDeviceColor(context.Context, *SendLampDeviceColorRequest) (*SendLampDeviceColorResponse, error)
	SendLampDeviceBrightness(context.Context, *SendLampDeviceBrightnessRequest) (*SendLampDeviceBrightnessResponse, error)
	SendLampDevicePulse(context.Context, *SendLampDevicePulseRequest) (*SendLampDevicePulseResponse, error)
	mustEmbedUnimplementedDevicesServiceServer()
}

// UnimplementedDevicesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDevicesServiceServer struct {
}

func (*UnimplementedDevicesServiceServer) CreateBatCaveDeviceSetting(context.Context, *CreateBatCaveDeviceSettingRequest) (*CreateBatCaveDeviceSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBatCaveDeviceSetting not implemented")
}
func (*UnimplementedDevicesServiceServer) GetBatCaveDeviceSetting(context.Context, *GetBatCaveDeviceSettingRequest) (*GetBatCaveDeviceSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatCaveDeviceSetting not implemented")
}
func (*UnimplementedDevicesServiceServer) UpdateBatCaveDeviceSetting(context.Context, *UpdateBatCaveDeviceSettingRequest) (*UpdateBatCaveDeviceSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatCaveDeviceSetting not implemented")
}
func (*UnimplementedDevicesServiceServer) SendLampDeviceOn(context.Context, *SendLampDeviceOnRequest) (*SendLampDeviceOnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLampDeviceOn not implemented")
}
func (*UnimplementedDevicesServiceServer) SendLampDeviceOff(context.Context, *SendLampDeviceOffRequest) (*SendLampDeviceOffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLampDeviceOff not implemented")
}
func (*UnimplementedDevicesServiceServer) SendLampDeviceColor(context.Context, *SendLampDeviceColorRequest) (*SendLampDeviceColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLampDeviceColor not implemented")
}
func (*UnimplementedDevicesServiceServer) SendLampDeviceBrightness(context.Context, *SendLampDeviceBrightnessRequest) (*SendLampDeviceBrightnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLampDeviceBrightness not implemented")
}
func (*UnimplementedDevicesServiceServer) SendLampDevicePulse(context.Context, *SendLampDevicePulseRequest) (*SendLampDevicePulseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLampDevicePulse not implemented")
}
func (*UnimplementedDevicesServiceServer) mustEmbedUnimplementedDevicesServiceServer() {}

func RegisterDevicesServiceServer(s *grpc.Server, srv DevicesServiceServer) {
	s.RegisterService(&_DevicesService_serviceDesc, srv)
}

func _DevicesService_CreateBatCaveDeviceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBatCaveDeviceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).CreateBatCaveDeviceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/CreateBatCaveDeviceSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).CreateBatCaveDeviceSetting(ctx, req.(*CreateBatCaveDeviceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_GetBatCaveDeviceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatCaveDeviceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).GetBatCaveDeviceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/GetBatCaveDeviceSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).GetBatCaveDeviceSetting(ctx, req.(*GetBatCaveDeviceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_UpdateBatCaveDeviceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBatCaveDeviceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).UpdateBatCaveDeviceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/UpdateBatCaveDeviceSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).UpdateBatCaveDeviceSetting(ctx, req.(*UpdateBatCaveDeviceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_SendLampDeviceOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLampDeviceOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).SendLampDeviceOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/SendLampDeviceOn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).SendLampDeviceOn(ctx, req.(*SendLampDeviceOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_SendLampDeviceOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLampDeviceOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).SendLampDeviceOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/SendLampDeviceOff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).SendLampDeviceOff(ctx, req.(*SendLampDeviceOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_SendLampDeviceColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLampDeviceColorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).SendLampDeviceColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/SendLampDeviceColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).SendLampDeviceColor(ctx, req.(*SendLampDeviceColorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_SendLampDeviceBrightness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLampDeviceBrightnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).SendLampDeviceBrightness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/SendLampDeviceBrightness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).SendLampDeviceBrightness(ctx, req.(*SendLampDeviceBrightnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_SendLampDevicePulse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLampDevicePulseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).SendLampDevicePulse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/SendLampDevicePulse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).SendLampDevicePulse(ctx, req.(*SendLampDevicePulseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DevicesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "devices_pb.DevicesService",
	HandlerType: (*DevicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBatCaveDeviceSetting",
			Handler:    _DevicesService_CreateBatCaveDeviceSetting_Handler,
		},
		{
			MethodName: "GetBatCaveDeviceSetting",
			Handler:    _DevicesService_GetBatCaveDeviceSetting_Handler,
		},
		{
			MethodName: "UpdateBatCaveDeviceSetting",
			Handler:    _DevicesService_UpdateBatCaveDeviceSetting_Handler,
		},
		{
			MethodName: "SendLampDeviceOn",
			Handler:    _DevicesService_SendLampDeviceOn_Handler,
		},
		{
			MethodName: "SendLampDeviceOff",
			Handler:    _DevicesService_SendLampDeviceOff_Handler,
		},
		{
			MethodName: "SendLampDeviceColor",
			Handler:    _DevicesService_SendLampDeviceColor_Handler,
		},
		{
			MethodName: "SendLampDeviceBrightness",
			Handler:    _DevicesService_SendLampDeviceBrightness_Handler,
		},
		{
			MethodName: "SendLampDevicePulse",
			Handler:    _DevicesService_SendLampDevicePulse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/devices/devices.proto",
}
