// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: internal/pb/devices/devices.proto

package devices_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateBatCaveDeviceSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac            string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *CreateBatCaveDeviceSettingRequest) Reset() {
	*x = CreateBatCaveDeviceSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatCaveDeviceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatCaveDeviceSettingRequest) ProtoMessage() {}

func (x *CreateBatCaveDeviceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatCaveDeviceSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateBatCaveDeviceSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBatCaveDeviceSettingRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateBatCaveDeviceSettingRequest) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type CreateBatCaveDeviceSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac            string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,3,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *CreateBatCaveDeviceSettingResponse) Reset() {
	*x = CreateBatCaveDeviceSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatCaveDeviceSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatCaveDeviceSettingResponse) ProtoMessage() {}

func (x *CreateBatCaveDeviceSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatCaveDeviceSettingResponse.ProtoReflect.Descriptor instead.
func (*CreateBatCaveDeviceSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBatCaveDeviceSettingResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateBatCaveDeviceSettingResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateBatCaveDeviceSettingResponse) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type GetBatCaveDeviceSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetBatCaveDeviceSettingRequest) Reset() {
	*x = GetBatCaveDeviceSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatCaveDeviceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatCaveDeviceSettingRequest) ProtoMessage() {}

func (x *GetBatCaveDeviceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatCaveDeviceSettingRequest.ProtoReflect.Descriptor instead.
func (*GetBatCaveDeviceSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatCaveDeviceSettingRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetBatCaveDeviceSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac            string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,3,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *GetBatCaveDeviceSettingResponse) Reset() {
	*x = GetBatCaveDeviceSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatCaveDeviceSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatCaveDeviceSettingResponse) ProtoMessage() {}

func (x *GetBatCaveDeviceSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatCaveDeviceSettingResponse.ProtoReflect.Descriptor instead.
func (*GetBatCaveDeviceSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatCaveDeviceSettingResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetBatCaveDeviceSettingResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetBatCaveDeviceSettingResponse) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type UpdateBatCaveDeviceSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *UpdateBatCaveDeviceSettingRequest) Reset() {
	*x = UpdateBatCaveDeviceSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBatCaveDeviceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatCaveDeviceSettingRequest) ProtoMessage() {}

func (x *UpdateBatCaveDeviceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatCaveDeviceSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBatCaveDeviceSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBatCaveDeviceSettingRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateBatCaveDeviceSettingRequest) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type UpdateBatCaveDeviceSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *UpdateBatCaveDeviceSettingResponse) Reset() {
	*x = UpdateBatCaveDeviceSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBatCaveDeviceSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatCaveDeviceSettingResponse) ProtoMessage() {}

func (x *UpdateBatCaveDeviceSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatCaveDeviceSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBatCaveDeviceSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBatCaveDeviceSettingResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateBatCaveDeviceSettingResponse) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

var File_internal_pb_devices_devices_proto protoreflect.FileDescriptor

var file_internal_pb_devices_devices_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x22,
	0x5d, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x6e,
	0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x30,
	0x0a, 0x1e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x6b, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65,
	0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x44,
	0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x5b, 0x0a,
	0x21, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70,
	0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x5c, 0x0a, 0x22, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c,
	0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x32, 0xfe, 0x02, 0x0a, 0x0e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x1a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x2e, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74,
	0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43,
	0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7b, 0x0a, 0x1a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74,
	0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_pb_devices_devices_proto_rawDescOnce sync.Once
	file_internal_pb_devices_devices_proto_rawDescData = file_internal_pb_devices_devices_proto_rawDesc
)

func file_internal_pb_devices_devices_proto_rawDescGZIP() []byte {
	file_internal_pb_devices_devices_proto_rawDescOnce.Do(func() {
		file_internal_pb_devices_devices_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_devices_devices_proto_rawDescData)
	})
	return file_internal_pb_devices_devices_proto_rawDescData
}

var file_internal_pb_devices_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_pb_devices_devices_proto_goTypes = []interface{}{
	(*CreateBatCaveDeviceSettingRequest)(nil),  // 0: devices_pb.CreateBatCaveDeviceSettingRequest
	(*CreateBatCaveDeviceSettingResponse)(nil), // 1: devices_pb.CreateBatCaveDeviceSettingResponse
	(*GetBatCaveDeviceSettingRequest)(nil),     // 2: devices_pb.GetBatCaveDeviceSettingRequest
	(*GetBatCaveDeviceSettingResponse)(nil),    // 3: devices_pb.GetBatCaveDeviceSettingResponse
	(*UpdateBatCaveDeviceSettingRequest)(nil),  // 4: devices_pb.UpdateBatCaveDeviceSettingRequest
	(*UpdateBatCaveDeviceSettingResponse)(nil), // 5: devices_pb.UpdateBatCaveDeviceSettingResponse
}
var file_internal_pb_devices_devices_proto_depIdxs = []int32{
	0, // 0: devices_pb.DevicesService.CreateBatCaveDeviceSetting:input_type -> devices_pb.CreateBatCaveDeviceSettingRequest
	2, // 1: devices_pb.DevicesService.GetBatCaveDeviceSetting:input_type -> devices_pb.GetBatCaveDeviceSettingRequest
	4, // 2: devices_pb.DevicesService.UpdateBatCaveDeviceSetting:input_type -> devices_pb.UpdateBatCaveDeviceSettingRequest
	1, // 3: devices_pb.DevicesService.CreateBatCaveDeviceSetting:output_type -> devices_pb.CreateBatCaveDeviceSettingResponse
	3, // 4: devices_pb.DevicesService.GetBatCaveDeviceSetting:output_type -> devices_pb.GetBatCaveDeviceSettingResponse
	5, // 5: devices_pb.DevicesService.UpdateBatCaveDeviceSetting:output_type -> devices_pb.UpdateBatCaveDeviceSettingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_devices_devices_proto_init() }
func file_internal_pb_devices_devices_proto_init() {
	if File_internal_pb_devices_devices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_devices_devices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatCaveDeviceSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatCaveDeviceSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatCaveDeviceSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatCaveDeviceSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBatCaveDeviceSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBatCaveDeviceSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_devices_devices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_devices_devices_proto_goTypes,
		DependencyIndexes: file_internal_pb_devices_devices_proto_depIdxs,
		MessageInfos:      file_internal_pb_devices_devices_proto_msgTypes,
	}.Build()
	File_internal_pb_devices_devices_proto = out.File
	file_internal_pb_devices_devices_proto_rawDesc = nil
	file_internal_pb_devices_devices_proto_goTypes = nil
	file_internal_pb_devices_devices_proto_depIdxs = nil
}
