// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: internal/pb/devices/devices.proto

package devices_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateBatCaveDeviceSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac            string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *CreateBatCaveDeviceSettingRequest) Reset() {
	*x = CreateBatCaveDeviceSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatCaveDeviceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatCaveDeviceSettingRequest) ProtoMessage() {}

func (x *CreateBatCaveDeviceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatCaveDeviceSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateBatCaveDeviceSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBatCaveDeviceSettingRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateBatCaveDeviceSettingRequest) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type CreateBatCaveDeviceSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac            string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,3,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *CreateBatCaveDeviceSettingResponse) Reset() {
	*x = CreateBatCaveDeviceSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatCaveDeviceSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatCaveDeviceSettingResponse) ProtoMessage() {}

func (x *CreateBatCaveDeviceSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatCaveDeviceSettingResponse.ProtoReflect.Descriptor instead.
func (*CreateBatCaveDeviceSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBatCaveDeviceSettingResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateBatCaveDeviceSettingResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateBatCaveDeviceSettingResponse) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type GetBatCaveDeviceSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetBatCaveDeviceSettingRequest) Reset() {
	*x = GetBatCaveDeviceSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatCaveDeviceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatCaveDeviceSettingRequest) ProtoMessage() {}

func (x *GetBatCaveDeviceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatCaveDeviceSettingRequest.ProtoReflect.Descriptor instead.
func (*GetBatCaveDeviceSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatCaveDeviceSettingRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetBatCaveDeviceSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac            string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,3,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *GetBatCaveDeviceSettingResponse) Reset() {
	*x = GetBatCaveDeviceSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatCaveDeviceSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatCaveDeviceSettingResponse) ProtoMessage() {}

func (x *GetBatCaveDeviceSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatCaveDeviceSettingResponse.ProtoReflect.Descriptor instead.
func (*GetBatCaveDeviceSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatCaveDeviceSettingResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetBatCaveDeviceSettingResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetBatCaveDeviceSettingResponse) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type UpdateBatCaveDeviceSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *UpdateBatCaveDeviceSettingRequest) Reset() {
	*x = UpdateBatCaveDeviceSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBatCaveDeviceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatCaveDeviceSettingRequest) ProtoMessage() {}

func (x *UpdateBatCaveDeviceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatCaveDeviceSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBatCaveDeviceSettingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBatCaveDeviceSettingRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateBatCaveDeviceSettingRequest) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type UpdateBatCaveDeviceSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeepSleepDelay uint32 `protobuf:"varint,2,opt,name=DeepSleepDelay,proto3" json:"DeepSleepDelay,omitempty"`
}

func (x *UpdateBatCaveDeviceSettingResponse) Reset() {
	*x = UpdateBatCaveDeviceSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBatCaveDeviceSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatCaveDeviceSettingResponse) ProtoMessage() {}

func (x *UpdateBatCaveDeviceSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatCaveDeviceSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBatCaveDeviceSettingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBatCaveDeviceSettingResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateBatCaveDeviceSettingResponse) GetDeepSleepDelay() uint32 {
	if x != nil {
		return x.DeepSleepDelay
	}
	return 0
}

type SendLampDeviceOnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *SendLampDeviceOnRequest) Reset() {
	*x = SendLampDeviceOnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceOnRequest) ProtoMessage() {}

func (x *SendLampDeviceOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceOnRequest.ProtoReflect.Descriptor instead.
func (*SendLampDeviceOnRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{6}
}

func (x *SendLampDeviceOnRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type SendLampDeviceOnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendLampDeviceOnResponse) Reset() {
	*x = SendLampDeviceOnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceOnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceOnResponse) ProtoMessage() {}

func (x *SendLampDeviceOnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceOnResponse.ProtoReflect.Descriptor instead.
func (*SendLampDeviceOnResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{7}
}

type SendLampDeviceOffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *SendLampDeviceOffRequest) Reset() {
	*x = SendLampDeviceOffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceOffRequest) ProtoMessage() {}

func (x *SendLampDeviceOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceOffRequest.ProtoReflect.Descriptor instead.
func (*SendLampDeviceOffRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{8}
}

func (x *SendLampDeviceOffRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type SendLampDeviceOffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendLampDeviceOffResponse) Reset() {
	*x = SendLampDeviceOffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceOffResponse) ProtoMessage() {}

func (x *SendLampDeviceOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceOffResponse.ProtoReflect.Descriptor instead.
func (*SendLampDeviceOffResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{9}
}

type SendLampDeviceToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *SendLampDeviceToggleRequest) Reset() {
	*x = SendLampDeviceToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceToggleRequest) ProtoMessage() {}

func (x *SendLampDeviceToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceToggleRequest.ProtoReflect.Descriptor instead.
func (*SendLampDeviceToggleRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{10}
}

func (x *SendLampDeviceToggleRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type SendLampDeviceToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendLampDeviceToggleResponse) Reset() {
	*x = SendLampDeviceToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceToggleResponse) ProtoMessage() {}

func (x *SendLampDeviceToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceToggleResponse.ProtoReflect.Descriptor instead.
func (*SendLampDeviceToggleResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{11}
}

type SendLampDeviceColorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac   string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Red   int32  `protobuf:"varint,2,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32  `protobuf:"varint,3,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32  `protobuf:"varint,4,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *SendLampDeviceColorRequest) Reset() {
	*x = SendLampDeviceColorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceColorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceColorRequest) ProtoMessage() {}

func (x *SendLampDeviceColorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceColorRequest.ProtoReflect.Descriptor instead.
func (*SendLampDeviceColorRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{12}
}

func (x *SendLampDeviceColorRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *SendLampDeviceColorRequest) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *SendLampDeviceColorRequest) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *SendLampDeviceColorRequest) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type SendLampDeviceColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendLampDeviceColorResponse) Reset() {
	*x = SendLampDeviceColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceColorResponse) ProtoMessage() {}

func (x *SendLampDeviceColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceColorResponse.ProtoReflect.Descriptor instead.
func (*SendLampDeviceColorResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{13}
}

type SendLampDeviceBrightnessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac        string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Brightness int32  `protobuf:"varint,2,opt,name=Brightness,proto3" json:"Brightness,omitempty"`
}

func (x *SendLampDeviceBrightnessRequest) Reset() {
	*x = SendLampDeviceBrightnessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceBrightnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceBrightnessRequest) ProtoMessage() {}

func (x *SendLampDeviceBrightnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceBrightnessRequest.ProtoReflect.Descriptor instead.
func (*SendLampDeviceBrightnessRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{14}
}

func (x *SendLampDeviceBrightnessRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *SendLampDeviceBrightnessRequest) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type SendLampDeviceBrightnessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendLampDeviceBrightnessResponse) Reset() {
	*x = SendLampDeviceBrightnessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDeviceBrightnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDeviceBrightnessResponse) ProtoMessage() {}

func (x *SendLampDeviceBrightnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDeviceBrightnessResponse.ProtoReflect.Descriptor instead.
func (*SendLampDeviceBrightnessResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{15}
}

type SendLampDevicePulseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac   string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Red   int32  `protobuf:"varint,2,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32  `protobuf:"varint,3,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32  `protobuf:"varint,4,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *SendLampDevicePulseRequest) Reset() {
	*x = SendLampDevicePulseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDevicePulseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDevicePulseRequest) ProtoMessage() {}

func (x *SendLampDevicePulseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDevicePulseRequest.ProtoReflect.Descriptor instead.
func (*SendLampDevicePulseRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{16}
}

func (x *SendLampDevicePulseRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *SendLampDevicePulseRequest) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *SendLampDevicePulseRequest) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *SendLampDevicePulseRequest) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type SendLampDevicePulseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendLampDevicePulseResponse) Reset() {
	*x = SendLampDevicePulseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_devices_devices_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLampDevicePulseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLampDevicePulseResponse) ProtoMessage() {}

func (x *SendLampDevicePulseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_devices_devices_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLampDevicePulseResponse.ProtoReflect.Descriptor instead.
func (*SendLampDevicePulseResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_devices_devices_proto_rawDescGZIP(), []int{17}
}

var File_internal_pb_devices_devices_proto protoreflect.FileDescriptor

var file_internal_pb_devices_devices_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x22,
	0x5d, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x6e,
	0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x30,
	0x0a, 0x1e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x6b, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65,
	0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x44,
	0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x5b, 0x0a,
	0x21, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70,
	0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x5c, 0x0a, 0x22, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x65, 0x6c,
	0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x44, 0x65, 0x65, 0x70, 0x53, 0x6c,
	0x65, 0x65, 0x70, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x2b, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64,
	0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d,
	0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2c, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22,
	0x1b, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x0a, 0x1b,
	0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x1e, 0x0a,
	0x1c, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6a, 0x0a,
	0x1a, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x10, 0x0a,
	0x03, 0x52, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x47, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x65, 0x6e,
	0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x1f, 0x53, 0x65, 0x6e, 0x64,
	0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1e, 0x0a,
	0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a,
	0x20, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x6a, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x52, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x1d, 0x0a,
	0x1b, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x75, 0x6c, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf1, 0x07, 0x0a,
	0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x7b, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x2e,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x5f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x7b, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76,
	0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2d,
	0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x74, 0x43, 0x61, 0x76, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a,
	0x10, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f,
	0x6e, 0x12, 0x23, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x11,
	0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x66,
	0x66, 0x12, 0x24, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x66, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4f, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69,
	0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x27, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x13, 0x53, 0x65, 0x6e,
	0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x12, 0x26, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x75, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x2b, 0x2e,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c,
	0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64,
	0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x12,
	0x26, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x75, 0x6c, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x5f, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x61, 0x6d, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_devices_devices_proto_rawDescOnce sync.Once
	file_internal_pb_devices_devices_proto_rawDescData = file_internal_pb_devices_devices_proto_rawDesc
)

func file_internal_pb_devices_devices_proto_rawDescGZIP() []byte {
	file_internal_pb_devices_devices_proto_rawDescOnce.Do(func() {
		file_internal_pb_devices_devices_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_devices_devices_proto_rawDescData)
	})
	return file_internal_pb_devices_devices_proto_rawDescData
}

var file_internal_pb_devices_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_pb_devices_devices_proto_goTypes = []interface{}{
	(*CreateBatCaveDeviceSettingRequest)(nil),  // 0: devices_pb.CreateBatCaveDeviceSettingRequest
	(*CreateBatCaveDeviceSettingResponse)(nil), // 1: devices_pb.CreateBatCaveDeviceSettingResponse
	(*GetBatCaveDeviceSettingRequest)(nil),     // 2: devices_pb.GetBatCaveDeviceSettingRequest
	(*GetBatCaveDeviceSettingResponse)(nil),    // 3: devices_pb.GetBatCaveDeviceSettingResponse
	(*UpdateBatCaveDeviceSettingRequest)(nil),  // 4: devices_pb.UpdateBatCaveDeviceSettingRequest
	(*UpdateBatCaveDeviceSettingResponse)(nil), // 5: devices_pb.UpdateBatCaveDeviceSettingResponse
	(*SendLampDeviceOnRequest)(nil),            // 6: devices_pb.SendLampDeviceOnRequest
	(*SendLampDeviceOnResponse)(nil),           // 7: devices_pb.SendLampDeviceOnResponse
	(*SendLampDeviceOffRequest)(nil),           // 8: devices_pb.SendLampDeviceOffRequest
	(*SendLampDeviceOffResponse)(nil),          // 9: devices_pb.SendLampDeviceOffResponse
	(*SendLampDeviceToggleRequest)(nil),        // 10: devices_pb.SendLampDeviceToggleRequest
	(*SendLampDeviceToggleResponse)(nil),       // 11: devices_pb.SendLampDeviceToggleResponse
	(*SendLampDeviceColorRequest)(nil),         // 12: devices_pb.SendLampDeviceColorRequest
	(*SendLampDeviceColorResponse)(nil),        // 13: devices_pb.SendLampDeviceColorResponse
	(*SendLampDeviceBrightnessRequest)(nil),    // 14: devices_pb.SendLampDeviceBrightnessRequest
	(*SendLampDeviceBrightnessResponse)(nil),   // 15: devices_pb.SendLampDeviceBrightnessResponse
	(*SendLampDevicePulseRequest)(nil),         // 16: devices_pb.SendLampDevicePulseRequest
	(*SendLampDevicePulseResponse)(nil),        // 17: devices_pb.SendLampDevicePulseResponse
}
var file_internal_pb_devices_devices_proto_depIdxs = []int32{
	0,  // 0: devices_pb.DevicesService.CreateBatCaveDeviceSetting:input_type -> devices_pb.CreateBatCaveDeviceSettingRequest
	2,  // 1: devices_pb.DevicesService.GetBatCaveDeviceSetting:input_type -> devices_pb.GetBatCaveDeviceSettingRequest
	4,  // 2: devices_pb.DevicesService.UpdateBatCaveDeviceSetting:input_type -> devices_pb.UpdateBatCaveDeviceSettingRequest
	6,  // 3: devices_pb.DevicesService.SendLampDeviceOn:input_type -> devices_pb.SendLampDeviceOnRequest
	8,  // 4: devices_pb.DevicesService.SendLampDeviceOff:input_type -> devices_pb.SendLampDeviceOffRequest
	10, // 5: devices_pb.DevicesService.SendLampDeviceToggle:input_type -> devices_pb.SendLampDeviceToggleRequest
	12, // 6: devices_pb.DevicesService.SendLampDeviceColor:input_type -> devices_pb.SendLampDeviceColorRequest
	14, // 7: devices_pb.DevicesService.SendLampDeviceBrightness:input_type -> devices_pb.SendLampDeviceBrightnessRequest
	16, // 8: devices_pb.DevicesService.SendLampDevicePulse:input_type -> devices_pb.SendLampDevicePulseRequest
	1,  // 9: devices_pb.DevicesService.CreateBatCaveDeviceSetting:output_type -> devices_pb.CreateBatCaveDeviceSettingResponse
	3,  // 10: devices_pb.DevicesService.GetBatCaveDeviceSetting:output_type -> devices_pb.GetBatCaveDeviceSettingResponse
	5,  // 11: devices_pb.DevicesService.UpdateBatCaveDeviceSetting:output_type -> devices_pb.UpdateBatCaveDeviceSettingResponse
	7,  // 12: devices_pb.DevicesService.SendLampDeviceOn:output_type -> devices_pb.SendLampDeviceOnResponse
	9,  // 13: devices_pb.DevicesService.SendLampDeviceOff:output_type -> devices_pb.SendLampDeviceOffResponse
	11, // 14: devices_pb.DevicesService.SendLampDeviceToggle:output_type -> devices_pb.SendLampDeviceToggleResponse
	13, // 15: devices_pb.DevicesService.SendLampDeviceColor:output_type -> devices_pb.SendLampDeviceColorResponse
	15, // 16: devices_pb.DevicesService.SendLampDeviceBrightness:output_type -> devices_pb.SendLampDeviceBrightnessResponse
	17, // 17: devices_pb.DevicesService.SendLampDevicePulse:output_type -> devices_pb.SendLampDevicePulseResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_devices_devices_proto_init() }
func file_internal_pb_devices_devices_proto_init() {
	if File_internal_pb_devices_devices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_devices_devices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatCaveDeviceSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatCaveDeviceSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatCaveDeviceSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatCaveDeviceSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBatCaveDeviceSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBatCaveDeviceSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceOnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceOnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceOffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceOffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceColorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceBrightnessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDeviceBrightnessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDevicePulseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_devices_devices_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendLampDevicePulseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_devices_devices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_devices_devices_proto_goTypes,
		DependencyIndexes: file_internal_pb_devices_devices_proto_depIdxs,
		MessageInfos:      file_internal_pb_devices_devices_proto_msgTypes,
	}.Build()
	File_internal_pb_devices_devices_proto = out.File
	file_internal_pb_devices_devices_proto_rawDesc = nil
	file_internal_pb_devices_devices_proto_goTypes = nil
	file_internal_pb_devices_devices_proto_depIdxs = nil
}
