// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package devices_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DevicesServiceClient is the client API for DevicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevicesServiceClient interface {
	CreateBatCaveDeviceSetting(ctx context.Context, in *CreateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*CreateBatCaveDeviceSettingResponse, error)
	GetBatCaveDeviceSetting(ctx context.Context, in *GetBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*GetBatCaveDeviceSettingResponse, error)
	UpdateBatCaveDeviceSetting(ctx context.Context, in *UpdateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*UpdateBatCaveDeviceSettingResponse, error)
}

type devicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevicesServiceClient(cc grpc.ClientConnInterface) DevicesServiceClient {
	return &devicesServiceClient{cc}
}

func (c *devicesServiceClient) CreateBatCaveDeviceSetting(ctx context.Context, in *CreateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*CreateBatCaveDeviceSettingResponse, error) {
	out := new(CreateBatCaveDeviceSettingResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/CreateBatCaveDeviceSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) GetBatCaveDeviceSetting(ctx context.Context, in *GetBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*GetBatCaveDeviceSettingResponse, error) {
	out := new(GetBatCaveDeviceSettingResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/GetBatCaveDeviceSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesServiceClient) UpdateBatCaveDeviceSetting(ctx context.Context, in *UpdateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*UpdateBatCaveDeviceSettingResponse, error) {
	out := new(UpdateBatCaveDeviceSettingResponse)
	err := c.cc.Invoke(ctx, "/devices_pb.DevicesService/UpdateBatCaveDeviceSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServiceServer is the server API for DevicesService service.
// All implementations must embed UnimplementedDevicesServiceServer
// for forward compatibility
type DevicesServiceServer interface {
	CreateBatCaveDeviceSetting(context.Context, *CreateBatCaveDeviceSettingRequest) (*CreateBatCaveDeviceSettingResponse, error)
	GetBatCaveDeviceSetting(context.Context, *GetBatCaveDeviceSettingRequest) (*GetBatCaveDeviceSettingResponse, error)
	UpdateBatCaveDeviceSetting(context.Context, *UpdateBatCaveDeviceSettingRequest) (*UpdateBatCaveDeviceSettingResponse, error)
	mustEmbedUnimplementedDevicesServiceServer()
}

// UnimplementedDevicesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDevicesServiceServer struct {
}

func (*UnimplementedDevicesServiceServer) CreateBatCaveDeviceSetting(context.Context, *CreateBatCaveDeviceSettingRequest) (*CreateBatCaveDeviceSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBatCaveDeviceSetting not implemented")
}
func (*UnimplementedDevicesServiceServer) GetBatCaveDeviceSetting(context.Context, *GetBatCaveDeviceSettingRequest) (*GetBatCaveDeviceSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatCaveDeviceSetting not implemented")
}
func (*UnimplementedDevicesServiceServer) UpdateBatCaveDeviceSetting(context.Context, *UpdateBatCaveDeviceSettingRequest) (*UpdateBatCaveDeviceSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatCaveDeviceSetting not implemented")
}
func (*UnimplementedDevicesServiceServer) mustEmbedUnimplementedDevicesServiceServer() {}

func RegisterDevicesServiceServer(s *grpc.Server, srv DevicesServiceServer) {
	s.RegisterService(&_DevicesService_serviceDesc, srv)
}

func _DevicesService_CreateBatCaveDeviceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBatCaveDeviceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).CreateBatCaveDeviceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/CreateBatCaveDeviceSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).CreateBatCaveDeviceSetting(ctx, req.(*CreateBatCaveDeviceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_GetBatCaveDeviceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatCaveDeviceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).GetBatCaveDeviceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/GetBatCaveDeviceSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).GetBatCaveDeviceSetting(ctx, req.(*GetBatCaveDeviceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevicesService_UpdateBatCaveDeviceSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBatCaveDeviceSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServiceServer).UpdateBatCaveDeviceSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devices_pb.DevicesService/UpdateBatCaveDeviceSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServiceServer).UpdateBatCaveDeviceSetting(ctx, req.(*UpdateBatCaveDeviceSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DevicesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "devices_pb.DevicesService",
	HandlerType: (*DevicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBatCaveDeviceSetting",
			Handler:    _DevicesService_CreateBatCaveDeviceSetting_Handler,
		},
		{
			MethodName: "GetBatCaveDeviceSetting",
			Handler:    _DevicesService_GetBatCaveDeviceSetting_Handler,
		},
		{
			MethodName: "UpdateBatCaveDeviceSetting",
			Handler:    _DevicesService_UpdateBatCaveDeviceSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/devices/devices.proto",
}
