// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/attach_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateAttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InteractionID string `protobuf:"bytes,1,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,2,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,3,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *CreateAttachRequest) Reset() {
	*x = CreateAttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachRequest) ProtoMessage() {}

func (x *CreateAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachRequest.ProtoReflect.Descriptor instead.
func (*CreateAttachRequest) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAttachRequest) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *CreateAttachRequest) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *CreateAttachRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type CreateAttachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *CreateAttachResponse) Reset() {
	*x = CreateAttachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachResponse) ProtoMessage() {}

func (x *CreateAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachResponse.ProtoReflect.Descriptor instead.
func (*CreateAttachResponse) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAttachResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateAttachResponse) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *CreateAttachResponse) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *CreateAttachResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type GetAttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetAttachRequest) Reset() {
	*x = GetAttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachRequest) ProtoMessage() {}

func (x *GetAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachRequest.ProtoReflect.Descriptor instead.
func (*GetAttachRequest) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetAttachRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetAttachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *GetAttachResponse) Reset() {
	*x = GetAttachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachResponse) ProtoMessage() {}

func (x *GetAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachResponse.ProtoReflect.Descriptor instead.
func (*GetAttachResponse) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetAttachResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetAttachResponse) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *GetAttachResponse) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *GetAttachResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type UpdateAttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *UpdateAttachRequest) Reset() {
	*x = UpdateAttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttachRequest) ProtoMessage() {}

func (x *UpdateAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttachRequest.ProtoReflect.Descriptor instead.
func (*UpdateAttachRequest) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAttachRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateAttachRequest) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *UpdateAttachRequest) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *UpdateAttachRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type UpdateAttachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InteractionID string `protobuf:"bytes,2,opt,name=InteractionID,proto3" json:"InteractionID,omitempty"`
	ConditionID   string `protobuf:"bytes,3,opt,name=ConditionID,proto3" json:"ConditionID,omitempty"`
	EventID       string `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
}

func (x *UpdateAttachResponse) Reset() {
	*x = UpdateAttachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttachResponse) ProtoMessage() {}

func (x *UpdateAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttachResponse.ProtoReflect.Descriptor instead.
func (*UpdateAttachResponse) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAttachResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateAttachResponse) GetInteractionID() string {
	if x != nil {
		return x.InteractionID
	}
	return ""
}

func (x *UpdateAttachResponse) GetConditionID() string {
	if x != nil {
		return x.ConditionID
	}
	return ""
}

func (x *UpdateAttachResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

type DeleteAttachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteAttachRequest) Reset() {
	*x = DeleteAttachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachRequest) ProtoMessage() {}

func (x *DeleteAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachRequest) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAttachRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteAttachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteAttachResponse) Reset() {
	*x = DeleteAttachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_attach_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachResponse) ProtoMessage() {}

func (x *DeleteAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_attach_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttachResponse) Descriptor() ([]byte, []int) {
	return file_messages_attach_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAttachResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_attach_messages_proto protoreflect.FileDescriptor

var file_messages_attach_messages_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70,
	0x62, 0x22, 0x77, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x88, 0x01, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x22, 0x87, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x88, 0x01, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x26, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_messages_attach_messages_proto_rawDescOnce sync.Once
	file_messages_attach_messages_proto_rawDescData = file_messages_attach_messages_proto_rawDesc
)

func file_messages_attach_messages_proto_rawDescGZIP() []byte {
	file_messages_attach_messages_proto_rawDescOnce.Do(func() {
		file_messages_attach_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_attach_messages_proto_rawDescData)
	})
	return file_messages_attach_messages_proto_rawDescData
}

var file_messages_attach_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_attach_messages_proto_goTypes = []interface{}{
	(*CreateAttachRequest)(nil),  // 0: interactions_pb.CreateAttachRequest
	(*CreateAttachResponse)(nil), // 1: interactions_pb.CreateAttachResponse
	(*GetAttachRequest)(nil),     // 2: interactions_pb.GetAttachRequest
	(*GetAttachResponse)(nil),    // 3: interactions_pb.GetAttachResponse
	(*UpdateAttachRequest)(nil),  // 4: interactions_pb.UpdateAttachRequest
	(*UpdateAttachResponse)(nil), // 5: interactions_pb.UpdateAttachResponse
	(*DeleteAttachRequest)(nil),  // 6: interactions_pb.DeleteAttachRequest
	(*DeleteAttachResponse)(nil), // 7: interactions_pb.DeleteAttachResponse
}
var file_messages_attach_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_attach_messages_proto_init() }
func file_messages_attach_messages_proto_init() {
	if File_messages_attach_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_attach_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_attach_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAttachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_attach_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_attach_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_attach_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_attach_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAttachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_attach_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAttachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_attach_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAttachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_attach_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_attach_messages_proto_goTypes,
		DependencyIndexes: file_messages_attach_messages_proto_depIdxs,
		MessageInfos:      file_messages_attach_messages_proto_msgTypes,
	}.Build()
	File_messages_attach_messages_proto = out.File
	file_messages_attach_messages_proto_rawDesc = nil
	file_messages_attach_messages_proto_goTypes = nil
	file_messages_attach_messages_proto_depIdxs = nil
}
