// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/keypad_conditions_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateKeypadConditionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac      string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	ButtonID int32  `protobuf:"varint,2,opt,name=ButtonID,proto3" json:"ButtonID,omitempty"`
}

func (x *CreateKeypadConditionRequest) Reset() {
	*x = CreateKeypadConditionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKeypadConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeypadConditionRequest) ProtoMessage() {}

func (x *CreateKeypadConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeypadConditionRequest.ProtoReflect.Descriptor instead.
func (*CreateKeypadConditionRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateKeypadConditionRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateKeypadConditionRequest) GetButtonID() int32 {
	if x != nil {
		return x.ButtonID
	}
	return 0
}

type CreateKeypadConditionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac      string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	ButtonID int32  `protobuf:"varint,3,opt,name=ButtonID,proto3" json:"ButtonID,omitempty"`
}

func (x *CreateKeypadConditionResponse) Reset() {
	*x = CreateKeypadConditionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKeypadConditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeypadConditionResponse) ProtoMessage() {}

func (x *CreateKeypadConditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeypadConditionResponse.ProtoReflect.Descriptor instead.
func (*CreateKeypadConditionResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKeypadConditionResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateKeypadConditionResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateKeypadConditionResponse) GetButtonID() int32 {
	if x != nil {
		return x.ButtonID
	}
	return 0
}

type GetKeypadConditionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetKeypadConditionRequest) Reset() {
	*x = GetKeypadConditionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeypadConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeypadConditionRequest) ProtoMessage() {}

func (x *GetKeypadConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeypadConditionRequest.ProtoReflect.Descriptor instead.
func (*GetKeypadConditionRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeypadConditionRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetKeypadConditionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac      string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	ButtonID int32  `protobuf:"varint,333,opt,name=ButtonID,proto3" json:"ButtonID,omitempty"`
}

func (x *GetKeypadConditionResponse) Reset() {
	*x = GetKeypadConditionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeypadConditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeypadConditionResponse) ProtoMessage() {}

func (x *GetKeypadConditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeypadConditionResponse.ProtoReflect.Descriptor instead.
func (*GetKeypadConditionResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeypadConditionResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetKeypadConditionResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetKeypadConditionResponse) GetButtonID() int32 {
	if x != nil {
		return x.ButtonID
	}
	return 0
}

type UpdateKeypadConditionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac      string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	ButtonID int32  `protobuf:"varint,3,opt,name=ButtonID,proto3" json:"ButtonID,omitempty"`
}

func (x *UpdateKeypadConditionRequest) Reset() {
	*x = UpdateKeypadConditionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKeypadConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeypadConditionRequest) ProtoMessage() {}

func (x *UpdateKeypadConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeypadConditionRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeypadConditionRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateKeypadConditionRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateKeypadConditionRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *UpdateKeypadConditionRequest) GetButtonID() int32 {
	if x != nil {
		return x.ButtonID
	}
	return 0
}

type UpdateKeypadConditionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac      string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	ButtonID int32  `protobuf:"varint,3,opt,name=ButtonID,proto3" json:"ButtonID,omitempty"`
}

func (x *UpdateKeypadConditionResponse) Reset() {
	*x = UpdateKeypadConditionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKeypadConditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeypadConditionResponse) ProtoMessage() {}

func (x *UpdateKeypadConditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeypadConditionResponse.ProtoReflect.Descriptor instead.
func (*UpdateKeypadConditionResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateKeypadConditionResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateKeypadConditionResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *UpdateKeypadConditionResponse) GetButtonID() int32 {
	if x != nil {
		return x.ButtonID
	}
	return 0
}

type DeleteKeypadConditionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteKeypadConditionRequest) Reset() {
	*x = DeleteKeypadConditionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeypadConditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeypadConditionRequest) ProtoMessage() {}

func (x *DeleteKeypadConditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeypadConditionRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeypadConditionRequest) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKeypadConditionRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteKeypadConditionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteKeypadConditionResponse) Reset() {
	*x = DeleteKeypadConditionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_keypad_conditions_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeypadConditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeypadConditionResponse) ProtoMessage() {}

func (x *DeleteKeypadConditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_keypad_conditions_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeypadConditionResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeypadConditionResponse) Descriptor() ([]byte, []int) {
	return file_messages_keypad_conditions_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKeypadConditionResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_keypad_conditions_messages_proto protoreflect.FileDescriptor

var file_messages_keypad_conditions_messages_proto_rawDesc = []byte{
	0x0a, 0x29, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6b, 0x65, 0x79, 0x70, 0x61,
	0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x4c, 0x0a, 0x1c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1a,
	0x0a, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x5d, 0x0a, 0x1d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1a, 0x0a,
	0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x5b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1b, 0x0a, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0xcd, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f,
	0x6e, 0x49, 0x44, 0x22, 0x5c, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49,
	0x44, 0x22, 0x5d, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61,
	0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x61, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x49, 0x44,
	0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x2f, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x70, 0x61, 0x64,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_keypad_conditions_messages_proto_rawDescOnce sync.Once
	file_messages_keypad_conditions_messages_proto_rawDescData = file_messages_keypad_conditions_messages_proto_rawDesc
)

func file_messages_keypad_conditions_messages_proto_rawDescGZIP() []byte {
	file_messages_keypad_conditions_messages_proto_rawDescOnce.Do(func() {
		file_messages_keypad_conditions_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_keypad_conditions_messages_proto_rawDescData)
	})
	return file_messages_keypad_conditions_messages_proto_rawDescData
}

var file_messages_keypad_conditions_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_keypad_conditions_messages_proto_goTypes = []interface{}{
	(*CreateKeypadConditionRequest)(nil),  // 0: interactions_pb.CreateKeypadConditionRequest
	(*CreateKeypadConditionResponse)(nil), // 1: interactions_pb.CreateKeypadConditionResponse
	(*GetKeypadConditionRequest)(nil),     // 2: interactions_pb.GetKeypadConditionRequest
	(*GetKeypadConditionResponse)(nil),    // 3: interactions_pb.GetKeypadConditionResponse
	(*UpdateKeypadConditionRequest)(nil),  // 4: interactions_pb.UpdateKeypadConditionRequest
	(*UpdateKeypadConditionResponse)(nil), // 5: interactions_pb.UpdateKeypadConditionResponse
	(*DeleteKeypadConditionRequest)(nil),  // 6: interactions_pb.DeleteKeypadConditionRequest
	(*DeleteKeypadConditionResponse)(nil), // 7: interactions_pb.DeleteKeypadConditionResponse
}
var file_messages_keypad_conditions_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_keypad_conditions_messages_proto_init() }
func file_messages_keypad_conditions_messages_proto_init() {
	if File_messages_keypad_conditions_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_keypad_conditions_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKeypadConditionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKeypadConditionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeypadConditionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeypadConditionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKeypadConditionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKeypadConditionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeypadConditionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_keypad_conditions_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeypadConditionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_keypad_conditions_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_keypad_conditions_messages_proto_goTypes,
		DependencyIndexes: file_messages_keypad_conditions_messages_proto_depIdxs,
		MessageInfos:      file_messages_keypad_conditions_messages_proto_msgTypes,
	}.Build()
	File_messages_keypad_conditions_messages_proto = out.File
	file_messages_keypad_conditions_messages_proto_rawDesc = nil
	file_messages_keypad_conditions_messages_proto_goTypes = nil
	file_messages_keypad_conditions_messages_proto_depIdxs = nil
}
