// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/lamp_brightness_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateLampBrightnessEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac        string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Brightness int32  `protobuf:"varint,2,opt,name=Brightness,proto3" json:"Brightness,omitempty"`
}

func (x *CreateLampBrightnessEventRequest) Reset() {
	*x = CreateLampBrightnessEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampBrightnessEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampBrightnessEventRequest) ProtoMessage() {}

func (x *CreateLampBrightnessEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampBrightnessEventRequest.ProtoReflect.Descriptor instead.
func (*CreateLampBrightnessEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLampBrightnessEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateLampBrightnessEventRequest) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type CreateLampBrightnessEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac        string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Brightness int32  `protobuf:"varint,3,opt,name=Brightness,proto3" json:"Brightness,omitempty"`
}

func (x *CreateLampBrightnessEventResponse) Reset() {
	*x = CreateLampBrightnessEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampBrightnessEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampBrightnessEventResponse) ProtoMessage() {}

func (x *CreateLampBrightnessEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampBrightnessEventResponse.ProtoReflect.Descriptor instead.
func (*CreateLampBrightnessEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLampBrightnessEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLampBrightnessEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateLampBrightnessEventResponse) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type GetLampBrightnessEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetLampBrightnessEventRequest) Reset() {
	*x = GetLampBrightnessEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampBrightnessEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampBrightnessEventRequest) ProtoMessage() {}

func (x *GetLampBrightnessEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampBrightnessEventRequest.ProtoReflect.Descriptor instead.
func (*GetLampBrightnessEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetLampBrightnessEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLampBrightnessEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac        string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Brightness int32  `protobuf:"varint,3,opt,name=Brightness,proto3" json:"Brightness,omitempty"`
}

func (x *GetLampBrightnessEventResponse) Reset() {
	*x = GetLampBrightnessEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampBrightnessEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampBrightnessEventResponse) ProtoMessage() {}

func (x *GetLampBrightnessEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampBrightnessEventResponse.ProtoReflect.Descriptor instead.
func (*GetLampBrightnessEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetLampBrightnessEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetLampBrightnessEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetLampBrightnessEventResponse) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type UpdateLampBrightnessEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac        string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Brightness int32  `protobuf:"varint,3,opt,name=Brightness,proto3" json:"Brightness,omitempty"`
}

func (x *UpdateLampBrightnessEventRequest) Reset() {
	*x = UpdateLampBrightnessEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampBrightnessEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampBrightnessEventRequest) ProtoMessage() {}

func (x *UpdateLampBrightnessEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampBrightnessEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateLampBrightnessEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLampBrightnessEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampBrightnessEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *UpdateLampBrightnessEventRequest) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type UpdateLampBrightnessEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac        string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Brightness int32  `protobuf:"varint,3,opt,name=Brightness,proto3" json:"Brightness,omitempty"`
}

func (x *UpdateLampBrightnessEventResponse) Reset() {
	*x = UpdateLampBrightnessEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampBrightnessEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampBrightnessEventResponse) ProtoMessage() {}

func (x *UpdateLampBrightnessEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampBrightnessEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateLampBrightnessEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLampBrightnessEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampBrightnessEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *UpdateLampBrightnessEventResponse) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type DeleteLampBrightnessEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampBrightnessEventRequest) Reset() {
	*x = DeleteLampBrightnessEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampBrightnessEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampBrightnessEventRequest) ProtoMessage() {}

func (x *DeleteLampBrightnessEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampBrightnessEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteLampBrightnessEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLampBrightnessEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLampBrightnessEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampBrightnessEventResponse) Reset() {
	*x = DeleteLampBrightnessEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampBrightnessEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampBrightnessEventResponse) ProtoMessage() {}

func (x *DeleteLampBrightnessEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_brightness_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampBrightnessEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteLampBrightnessEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_brightness_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLampBrightnessEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_lamp_brightness_events_messages_proto protoreflect.FileDescriptor

var file_messages_lamp_brightness_events_messages_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x5f,
	0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70,
	0x62, 0x22, 0x54, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x42,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x42, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x65, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x61, 0x6d, 0x70, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1e,
	0x0a, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x2f,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x62, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x61, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x22, 0x64, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d,
	0x70, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x42,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x65, 0x0a, 0x21, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73,
	0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63,
	0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x22, 0x32, 0x0a, 0x20, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x42, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x33, 0x0a, 0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61,
	0x6d, 0x70, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_lamp_brightness_events_messages_proto_rawDescOnce sync.Once
	file_messages_lamp_brightness_events_messages_proto_rawDescData = file_messages_lamp_brightness_events_messages_proto_rawDesc
)

func file_messages_lamp_brightness_events_messages_proto_rawDescGZIP() []byte {
	file_messages_lamp_brightness_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_lamp_brightness_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_lamp_brightness_events_messages_proto_rawDescData)
	})
	return file_messages_lamp_brightness_events_messages_proto_rawDescData
}

var file_messages_lamp_brightness_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_lamp_brightness_events_messages_proto_goTypes = []interface{}{
	(*CreateLampBrightnessEventRequest)(nil),  // 0: interactions_pb.CreateLampBrightnessEventRequest
	(*CreateLampBrightnessEventResponse)(nil), // 1: interactions_pb.CreateLampBrightnessEventResponse
	(*GetLampBrightnessEventRequest)(nil),     // 2: interactions_pb.GetLampBrightnessEventRequest
	(*GetLampBrightnessEventResponse)(nil),    // 3: interactions_pb.GetLampBrightnessEventResponse
	(*UpdateLampBrightnessEventRequest)(nil),  // 4: interactions_pb.UpdateLampBrightnessEventRequest
	(*UpdateLampBrightnessEventResponse)(nil), // 5: interactions_pb.UpdateLampBrightnessEventResponse
	(*DeleteLampBrightnessEventRequest)(nil),  // 6: interactions_pb.DeleteLampBrightnessEventRequest
	(*DeleteLampBrightnessEventResponse)(nil), // 7: interactions_pb.DeleteLampBrightnessEventResponse
}
var file_messages_lamp_brightness_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_lamp_brightness_events_messages_proto_init() }
func file_messages_lamp_brightness_events_messages_proto_init() {
	if File_messages_lamp_brightness_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_lamp_brightness_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampBrightnessEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_brightness_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampBrightnessEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_brightness_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampBrightnessEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_brightness_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampBrightnessEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_brightness_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampBrightnessEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_brightness_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampBrightnessEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_brightness_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampBrightnessEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_brightness_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampBrightnessEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_lamp_brightness_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_lamp_brightness_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_lamp_brightness_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_lamp_brightness_events_messages_proto_msgTypes,
	}.Build()
	File_messages_lamp_brightness_events_messages_proto = out.File
	file_messages_lamp_brightness_events_messages_proto_rawDesc = nil
	file_messages_lamp_brightness_events_messages_proto_goTypes = nil
	file_messages_lamp_brightness_events_messages_proto_depIdxs = nil
}
