// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/lamp_auto_brightness_off_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateLampAutoBrightnessOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampAutoBrightnessOffEventRequest) Reset() {
	*x = CreateLampAutoBrightnessOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampAutoBrightnessOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampAutoBrightnessOffEventRequest) ProtoMessage() {}

func (x *CreateLampAutoBrightnessOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampAutoBrightnessOffEventRequest.ProtoReflect.Descriptor instead.
func (*CreateLampAutoBrightnessOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLampAutoBrightnessOffEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type CreateLampAutoBrightnessOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampAutoBrightnessOffEventResponse) Reset() {
	*x = CreateLampAutoBrightnessOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampAutoBrightnessOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampAutoBrightnessOffEventResponse) ProtoMessage() {}

func (x *CreateLampAutoBrightnessOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampAutoBrightnessOffEventResponse.ProtoReflect.Descriptor instead.
func (*CreateLampAutoBrightnessOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLampAutoBrightnessOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLampAutoBrightnessOffEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type GetLampAutoBrightnessOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetLampAutoBrightnessOffEventRequest) Reset() {
	*x = GetLampAutoBrightnessOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampAutoBrightnessOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampAutoBrightnessOffEventRequest) ProtoMessage() {}

func (x *GetLampAutoBrightnessOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampAutoBrightnessOffEventRequest.ProtoReflect.Descriptor instead.
func (*GetLampAutoBrightnessOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetLampAutoBrightnessOffEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLampAutoBrightnessOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *GetLampAutoBrightnessOffEventResponse) Reset() {
	*x = GetLampAutoBrightnessOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampAutoBrightnessOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampAutoBrightnessOffEventResponse) ProtoMessage() {}

func (x *GetLampAutoBrightnessOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampAutoBrightnessOffEventResponse.ProtoReflect.Descriptor instead.
func (*GetLampAutoBrightnessOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetLampAutoBrightnessOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetLampAutoBrightnessOffEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampAutoBrightnessOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampAutoBrightnessOffEventRequest) Reset() {
	*x = UpdateLampAutoBrightnessOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampAutoBrightnessOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampAutoBrightnessOffEventRequest) ProtoMessage() {}

func (x *UpdateLampAutoBrightnessOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampAutoBrightnessOffEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateLampAutoBrightnessOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLampAutoBrightnessOffEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampAutoBrightnessOffEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampAutoBrightnessOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampAutoBrightnessOffEventResponse) Reset() {
	*x = UpdateLampAutoBrightnessOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampAutoBrightnessOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampAutoBrightnessOffEventResponse) ProtoMessage() {}

func (x *UpdateLampAutoBrightnessOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampAutoBrightnessOffEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateLampAutoBrightnessOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLampAutoBrightnessOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampAutoBrightnessOffEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type DeleteLampAutoBrightnessOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampAutoBrightnessOffEventRequest) Reset() {
	*x = DeleteLampAutoBrightnessOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampAutoBrightnessOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampAutoBrightnessOffEventRequest) ProtoMessage() {}

func (x *DeleteLampAutoBrightnessOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampAutoBrightnessOffEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteLampAutoBrightnessOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLampAutoBrightnessOffEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLampAutoBrightnessOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampAutoBrightnessOffEventResponse) Reset() {
	*x = DeleteLampAutoBrightnessOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampAutoBrightnessOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampAutoBrightnessOffEventResponse) ProtoMessage() {}

func (x *DeleteLampAutoBrightnessOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampAutoBrightnessOffEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteLampAutoBrightnessOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLampAutoBrightnessOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_lamp_auto_brightness_off_events_messages_proto protoreflect.FileDescriptor

var file_messages_lamp_auto_brightness_off_events_messages_proto_rawDesc = []byte{
	0x0a, 0x37, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x5f,
	0x61, 0x75, 0x74, 0x6f, 0x5f, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x5f,
	0x6f, 0x66, 0x66, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x3b, 0x0a, 0x27, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x4c, 0x0a, 0x28, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x36, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70,
	0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x66,
	0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x49, 0x0a,
	0x25, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x4b, 0x0a, 0x27, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x4c, 0x0a, 0x28, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73,
	0x73, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x61, 0x63, 0x22, 0x39, 0x0a, 0x27, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x6d,
	0x70, 0x41, 0x75, 0x74, 0x6f, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f,
	0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x3a,
	0x0a, 0x28, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x41, 0x75, 0x74, 0x6f,
	0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescOnce sync.Once
	file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescData = file_messages_lamp_auto_brightness_off_events_messages_proto_rawDesc
)

func file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescGZIP() []byte {
	file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescData)
	})
	return file_messages_lamp_auto_brightness_off_events_messages_proto_rawDescData
}

var file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_lamp_auto_brightness_off_events_messages_proto_goTypes = []interface{}{
	(*CreateLampAutoBrightnessOffEventRequest)(nil),  // 0: interactions_pb.CreateLampAutoBrightnessOffEventRequest
	(*CreateLampAutoBrightnessOffEventResponse)(nil), // 1: interactions_pb.CreateLampAutoBrightnessOffEventResponse
	(*GetLampAutoBrightnessOffEventRequest)(nil),     // 2: interactions_pb.GetLampAutoBrightnessOffEventRequest
	(*GetLampAutoBrightnessOffEventResponse)(nil),    // 3: interactions_pb.GetLampAutoBrightnessOffEventResponse
	(*UpdateLampAutoBrightnessOffEventRequest)(nil),  // 4: interactions_pb.UpdateLampAutoBrightnessOffEventRequest
	(*UpdateLampAutoBrightnessOffEventResponse)(nil), // 5: interactions_pb.UpdateLampAutoBrightnessOffEventResponse
	(*DeleteLampAutoBrightnessOffEventRequest)(nil),  // 6: interactions_pb.DeleteLampAutoBrightnessOffEventRequest
	(*DeleteLampAutoBrightnessOffEventResponse)(nil), // 7: interactions_pb.DeleteLampAutoBrightnessOffEventResponse
}
var file_messages_lamp_auto_brightness_off_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_lamp_auto_brightness_off_events_messages_proto_init() }
func file_messages_lamp_auto_brightness_off_events_messages_proto_init() {
	if File_messages_lamp_auto_brightness_off_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampAutoBrightnessOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampAutoBrightnessOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampAutoBrightnessOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampAutoBrightnessOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampAutoBrightnessOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampAutoBrightnessOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampAutoBrightnessOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampAutoBrightnessOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_lamp_auto_brightness_off_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_lamp_auto_brightness_off_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_lamp_auto_brightness_off_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_lamp_auto_brightness_off_events_messages_proto_msgTypes,
	}.Build()
	File_messages_lamp_auto_brightness_off_events_messages_proto = out.File
	file_messages_lamp_auto_brightness_off_events_messages_proto_rawDesc = nil
	file_messages_lamp_auto_brightness_off_events_messages_proto_goTypes = nil
	file_messages_lamp_auto_brightness_off_events_messages_proto_depIdxs = nil
}
