// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/lamp_color_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateLampColorEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac   string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Red   int32  `protobuf:"varint,2,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32  `protobuf:"varint,3,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32  `protobuf:"varint,4,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *CreateLampColorEventRequest) Reset() {
	*x = CreateLampColorEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampColorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampColorEventRequest) ProtoMessage() {}

func (x *CreateLampColorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampColorEventRequest.ProtoReflect.Descriptor instead.
func (*CreateLampColorEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLampColorEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateLampColorEventRequest) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *CreateLampColorEventRequest) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *CreateLampColorEventRequest) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type CreateLampColorEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac   string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Red   int32  `protobuf:"varint,3,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32  `protobuf:"varint,4,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32  `protobuf:"varint,5,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *CreateLampColorEventResponse) Reset() {
	*x = CreateLampColorEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampColorEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampColorEventResponse) ProtoMessage() {}

func (x *CreateLampColorEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampColorEventResponse.ProtoReflect.Descriptor instead.
func (*CreateLampColorEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLampColorEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLampColorEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CreateLampColorEventResponse) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *CreateLampColorEventResponse) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *CreateLampColorEventResponse) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type GetLampColorEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetLampColorEventRequest) Reset() {
	*x = GetLampColorEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampColorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampColorEventRequest) ProtoMessage() {}

func (x *GetLampColorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampColorEventRequest.ProtoReflect.Descriptor instead.
func (*GetLampColorEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetLampColorEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLampColorEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac   string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Red   int32  `protobuf:"varint,3,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32  `protobuf:"varint,4,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32  `protobuf:"varint,5,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *GetLampColorEventResponse) Reset() {
	*x = GetLampColorEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampColorEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampColorEventResponse) ProtoMessage() {}

func (x *GetLampColorEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampColorEventResponse.ProtoReflect.Descriptor instead.
func (*GetLampColorEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetLampColorEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetLampColorEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetLampColorEventResponse) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *GetLampColorEventResponse) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *GetLampColorEventResponse) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type UpdateLampColorEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac   string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Red   int32  `protobuf:"varint,3,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32  `protobuf:"varint,4,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32  `protobuf:"varint,5,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *UpdateLampColorEventRequest) Reset() {
	*x = UpdateLampColorEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampColorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampColorEventRequest) ProtoMessage() {}

func (x *UpdateLampColorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampColorEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateLampColorEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLampColorEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampColorEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *UpdateLampColorEventRequest) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *UpdateLampColorEventRequest) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *UpdateLampColorEventRequest) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type UpdateLampColorEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac   string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Red   int32  `protobuf:"varint,3,opt,name=Red,proto3" json:"Red,omitempty"`
	Green int32  `protobuf:"varint,4,opt,name=Green,proto3" json:"Green,omitempty"`
	Blue  int32  `protobuf:"varint,5,opt,name=Blue,proto3" json:"Blue,omitempty"`
}

func (x *UpdateLampColorEventResponse) Reset() {
	*x = UpdateLampColorEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampColorEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampColorEventResponse) ProtoMessage() {}

func (x *UpdateLampColorEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampColorEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateLampColorEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLampColorEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampColorEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *UpdateLampColorEventResponse) GetRed() int32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *UpdateLampColorEventResponse) GetGreen() int32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *UpdateLampColorEventResponse) GetBlue() int32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type DeleteLampColorEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampColorEventRequest) Reset() {
	*x = DeleteLampColorEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampColorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampColorEventRequest) ProtoMessage() {}

func (x *DeleteLampColorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampColorEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteLampColorEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLampColorEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLampColorEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampColorEventResponse) Reset() {
	*x = DeleteLampColorEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_color_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampColorEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampColorEventResponse) ProtoMessage() {}

func (x *DeleteLampColorEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_color_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampColorEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteLampColorEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_color_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLampColorEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_lamp_color_events_messages_proto protoreflect.FileDescriptor

var file_messages_lamp_color_events_messages_proto_rawDesc = []byte{
	0x0a, 0x29, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x5f,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x6b, 0x0a, 0x1b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x10, 0x0a,
	0x03, 0x52, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x47, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x7c, 0x0a, 0x1c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x52,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72,
	0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x79, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x61, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x52, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c,
	0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x7b,
	0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12,
	0x10, 0x0a, 0x03, 0x52, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x7c, 0x0a, 0x1c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x10, 0x0a,
	0x03, 0x52, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x47, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_lamp_color_events_messages_proto_rawDescOnce sync.Once
	file_messages_lamp_color_events_messages_proto_rawDescData = file_messages_lamp_color_events_messages_proto_rawDesc
)

func file_messages_lamp_color_events_messages_proto_rawDescGZIP() []byte {
	file_messages_lamp_color_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_lamp_color_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_lamp_color_events_messages_proto_rawDescData)
	})
	return file_messages_lamp_color_events_messages_proto_rawDescData
}

var file_messages_lamp_color_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_lamp_color_events_messages_proto_goTypes = []interface{}{
	(*CreateLampColorEventRequest)(nil),  // 0: interactions_pb.CreateLampColorEventRequest
	(*CreateLampColorEventResponse)(nil), // 1: interactions_pb.CreateLampColorEventResponse
	(*GetLampColorEventRequest)(nil),     // 2: interactions_pb.GetLampColorEventRequest
	(*GetLampColorEventResponse)(nil),    // 3: interactions_pb.GetLampColorEventResponse
	(*UpdateLampColorEventRequest)(nil),  // 4: interactions_pb.UpdateLampColorEventRequest
	(*UpdateLampColorEventResponse)(nil), // 5: interactions_pb.UpdateLampColorEventResponse
	(*DeleteLampColorEventRequest)(nil),  // 6: interactions_pb.DeleteLampColorEventRequest
	(*DeleteLampColorEventResponse)(nil), // 7: interactions_pb.DeleteLampColorEventResponse
}
var file_messages_lamp_color_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_lamp_color_events_messages_proto_init() }
func file_messages_lamp_color_events_messages_proto_init() {
	if File_messages_lamp_color_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_lamp_color_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampColorEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_color_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampColorEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_color_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampColorEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_color_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampColorEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_color_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampColorEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_color_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampColorEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_color_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampColorEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_color_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampColorEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_lamp_color_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_lamp_color_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_lamp_color_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_lamp_color_events_messages_proto_msgTypes,
	}.Build()
	File_messages_lamp_color_events_messages_proto = out.File
	file_messages_lamp_color_events_messages_proto_rawDesc = nil
	file_messages_lamp_color_events_messages_proto_goTypes = nil
	file_messages_lamp_color_events_messages_proto_depIdxs = nil
}
