// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: messages/lamp_off_events_messages.proto

package interactions_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateLampOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampOffEventRequest) Reset() {
	*x = CreateLampOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampOffEventRequest) ProtoMessage() {}

func (x *CreateLampOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampOffEventRequest.ProtoReflect.Descriptor instead.
func (*CreateLampOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLampOffEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type CreateLampOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *CreateLampOffEventResponse) Reset() {
	*x = CreateLampOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLampOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLampOffEventResponse) ProtoMessage() {}

func (x *CreateLampOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLampOffEventResponse.ProtoReflect.Descriptor instead.
func (*CreateLampOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLampOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateLampOffEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type GetLampOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetLampOffEventRequest) Reset() {
	*x = GetLampOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampOffEventRequest) ProtoMessage() {}

func (x *GetLampOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampOffEventRequest.ProtoReflect.Descriptor instead.
func (*GetLampOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetLampOffEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLampOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *GetLampOffEventResponse) Reset() {
	*x = GetLampOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLampOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLampOffEventResponse) ProtoMessage() {}

func (x *GetLampOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLampOffEventResponse.ProtoReflect.Descriptor instead.
func (*GetLampOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetLampOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetLampOffEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampOffEventRequest) Reset() {
	*x = UpdateLampOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampOffEventRequest) ProtoMessage() {}

func (x *UpdateLampOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampOffEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateLampOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLampOffEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampOffEventRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type UpdateLampOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Mac string `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
}

func (x *UpdateLampOffEventResponse) Reset() {
	*x = UpdateLampOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLampOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLampOffEventResponse) ProtoMessage() {}

func (x *UpdateLampOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLampOffEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateLampOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLampOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateLampOffEventResponse) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type DeleteLampOffEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampOffEventRequest) Reset() {
	*x = DeleteLampOffEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampOffEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampOffEventRequest) ProtoMessage() {}

func (x *DeleteLampOffEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampOffEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteLampOffEventRequest) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLampOffEventRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteLampOffEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteLampOffEventResponse) Reset() {
	*x = DeleteLampOffEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_lamp_off_events_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLampOffEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLampOffEventResponse) ProtoMessage() {}

func (x *DeleteLampOffEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_lamp_off_events_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLampOffEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteLampOffEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_lamp_off_events_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLampOffEventResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_messages_lamp_off_events_messages_proto protoreflect.FileDescriptor

var file_messages_lamp_off_events_messages_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6c, 0x61, 0x6d, 0x70, 0x5f,
	0x6f, 0x66, 0x66, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x22, 0x2d, 0x0a, 0x19, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x3e, 0x0a, 0x1a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x3b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66,
	0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63,
	0x22, 0x3d, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66,
	0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22,
	0x3e, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x22,
	0x2b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x2c, 0x0a, 0x1a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x6d, 0x70, 0x4f, 0x66, 0x66, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x3b,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_lamp_off_events_messages_proto_rawDescOnce sync.Once
	file_messages_lamp_off_events_messages_proto_rawDescData = file_messages_lamp_off_events_messages_proto_rawDesc
)

func file_messages_lamp_off_events_messages_proto_rawDescGZIP() []byte {
	file_messages_lamp_off_events_messages_proto_rawDescOnce.Do(func() {
		file_messages_lamp_off_events_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_lamp_off_events_messages_proto_rawDescData)
	})
	return file_messages_lamp_off_events_messages_proto_rawDescData
}

var file_messages_lamp_off_events_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_lamp_off_events_messages_proto_goTypes = []interface{}{
	(*CreateLampOffEventRequest)(nil),  // 0: interactions_pb.CreateLampOffEventRequest
	(*CreateLampOffEventResponse)(nil), // 1: interactions_pb.CreateLampOffEventResponse
	(*GetLampOffEventRequest)(nil),     // 2: interactions_pb.GetLampOffEventRequest
	(*GetLampOffEventResponse)(nil),    // 3: interactions_pb.GetLampOffEventResponse
	(*UpdateLampOffEventRequest)(nil),  // 4: interactions_pb.UpdateLampOffEventRequest
	(*UpdateLampOffEventResponse)(nil), // 5: interactions_pb.UpdateLampOffEventResponse
	(*DeleteLampOffEventRequest)(nil),  // 6: interactions_pb.DeleteLampOffEventRequest
	(*DeleteLampOffEventResponse)(nil), // 7: interactions_pb.DeleteLampOffEventResponse
}
var file_messages_lamp_off_events_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_lamp_off_events_messages_proto_init() }
func file_messages_lamp_off_events_messages_proto_init() {
	if File_messages_lamp_off_events_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_lamp_off_events_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_off_events_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLampOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_off_events_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_off_events_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLampOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_off_events_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_off_events_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLampOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_off_events_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampOffEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_lamp_off_events_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLampOffEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_lamp_off_events_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_lamp_off_events_messages_proto_goTypes,
		DependencyIndexes: file_messages_lamp_off_events_messages_proto_depIdxs,
		MessageInfos:      file_messages_lamp_off_events_messages_proto_msgTypes,
	}.Build()
	File_messages_lamp_off_events_messages_proto = out.File
	file_messages_lamp_off_events_messages_proto_rawDesc = nil
	file_messages_lamp_off_events_messages_proto_goTypes = nil
	file_messages_lamp_off_events_messages_proto_depIdxs = nil
}
