// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/pb/devices/devices_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	devices_pb "github.com/io-1/kuiper/pkg/pb/devices"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockDevicesServiceClient is a mock of DevicesServiceClient interface.
type MockDevicesServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockDevicesServiceClientMockRecorder
}

// MockDevicesServiceClientMockRecorder is the mock recorder for MockDevicesServiceClient.
type MockDevicesServiceClientMockRecorder struct {
	mock *MockDevicesServiceClient
}

// NewMockDevicesServiceClient creates a new mock instance.
func NewMockDevicesServiceClient(ctrl *gomock.Controller) *MockDevicesServiceClient {
	mock := &MockDevicesServiceClient{ctrl: ctrl}
	mock.recorder = &MockDevicesServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevicesServiceClient) EXPECT() *MockDevicesServiceClientMockRecorder {
	return m.recorder
}

// CreateBatCaveDeviceSetting mocks base method.
func (m *MockDevicesServiceClient) CreateBatCaveDeviceSetting(ctx context.Context, in *devices_pb.CreateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*devices_pb.CreateBatCaveDeviceSettingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateBatCaveDeviceSetting", varargs...)
	ret0, _ := ret[0].(*devices_pb.CreateBatCaveDeviceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatCaveDeviceSetting indicates an expected call of CreateBatCaveDeviceSetting.
func (mr *MockDevicesServiceClientMockRecorder) CreateBatCaveDeviceSetting(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatCaveDeviceSetting", reflect.TypeOf((*MockDevicesServiceClient)(nil).CreateBatCaveDeviceSetting), varargs...)
}

// GetBatCaveDeviceSetting mocks base method.
func (m *MockDevicesServiceClient) GetBatCaveDeviceSetting(ctx context.Context, in *devices_pb.GetBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*devices_pb.GetBatCaveDeviceSettingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBatCaveDeviceSetting", varargs...)
	ret0, _ := ret[0].(*devices_pb.GetBatCaveDeviceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatCaveDeviceSetting indicates an expected call of GetBatCaveDeviceSetting.
func (mr *MockDevicesServiceClientMockRecorder) GetBatCaveDeviceSetting(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatCaveDeviceSetting", reflect.TypeOf((*MockDevicesServiceClient)(nil).GetBatCaveDeviceSetting), varargs...)
}

// UpdateBatCaveDeviceSetting mocks base method.
func (m *MockDevicesServiceClient) UpdateBatCaveDeviceSetting(ctx context.Context, in *devices_pb.UpdateBatCaveDeviceSettingRequest, opts ...grpc.CallOption) (*devices_pb.UpdateBatCaveDeviceSettingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBatCaveDeviceSetting", varargs...)
	ret0, _ := ret[0].(*devices_pb.UpdateBatCaveDeviceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBatCaveDeviceSetting indicates an expected call of UpdateBatCaveDeviceSetting.
func (mr *MockDevicesServiceClientMockRecorder) UpdateBatCaveDeviceSetting(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatCaveDeviceSetting", reflect.TypeOf((*MockDevicesServiceClient)(nil).UpdateBatCaveDeviceSetting), varargs...)
}

// SendLampDeviceOn mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceOn(ctx context.Context, in *devices_pb.SendLampDeviceOnRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceOnResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceOn", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceOnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceOn indicates an expected call of SendLampDeviceOn.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceOn(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceOn", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceOn), varargs...)
}

// SendLampDeviceOff mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceOff(ctx context.Context, in *devices_pb.SendLampDeviceOffRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceOffResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceOff", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceOffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceOff indicates an expected call of SendLampDeviceOff.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceOff(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceOff", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceOff), varargs...)
}

// SendLampDeviceToggle mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceToggle(ctx context.Context, in *devices_pb.SendLampDeviceToggleRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceToggleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceToggle", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceToggleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceToggle indicates an expected call of SendLampDeviceToggle.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceToggle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceToggle", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceToggle), varargs...)
}

// SendLampDeviceColor mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceColor(ctx context.Context, in *devices_pb.SendLampDeviceColorRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceColorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceColor", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceColorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceColor indicates an expected call of SendLampDeviceColor.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceColor(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceColor", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceColor), varargs...)
}

// SendLampDeviceBrightness mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceBrightness(ctx context.Context, in *devices_pb.SendLampDeviceBrightnessRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceBrightnessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceBrightness", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceBrightnessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceBrightness indicates an expected call of SendLampDeviceBrightness.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceBrightness(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceBrightness", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceBrightness), varargs...)
}

// SendLampDeviceAutoBrightnessOn mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceAutoBrightnessOn(ctx context.Context, in *devices_pb.SendLampDeviceAutoBrightnessOnRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceAutoBrightnessOnResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceAutoBrightnessOn", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceAutoBrightnessOnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceAutoBrightnessOn indicates an expected call of SendLampDeviceAutoBrightnessOn.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceAutoBrightnessOn(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceAutoBrightnessOn", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceAutoBrightnessOn), varargs...)
}

// SendLampDeviceAutoBrightnessOff mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceAutoBrightnessOff(ctx context.Context, in *devices_pb.SendLampDeviceAutoBrightnessOffRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceAutoBrightnessOffResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceAutoBrightnessOff", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceAutoBrightnessOffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceAutoBrightnessOff indicates an expected call of SendLampDeviceAutoBrightnessOff.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceAutoBrightnessOff(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceAutoBrightnessOff", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceAutoBrightnessOff), varargs...)
}

// SendLampDeviceAutoBrightnessToggle mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceAutoBrightnessToggle(ctx context.Context, in *devices_pb.SendLampDeviceAutoBrightnessToggleRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceAutoBrightnessToggleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceAutoBrightnessToggle", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceAutoBrightnessToggleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceAutoBrightnessToggle indicates an expected call of SendLampDeviceAutoBrightnessToggle.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceAutoBrightnessToggle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceAutoBrightnessToggle", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceAutoBrightnessToggle), varargs...)
}

// SendLampDevicePulse mocks base method.
func (m *MockDevicesServiceClient) SendLampDevicePulse(ctx context.Context, in *devices_pb.SendLampDevicePulseRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDevicePulseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDevicePulse", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDevicePulseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDevicePulse indicates an expected call of SendLampDevicePulse.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDevicePulse(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDevicePulse", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDevicePulse), varargs...)
}

// SendLampDeviceMeteor mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceMeteor(ctx context.Context, in *devices_pb.SendLampDeviceMeteorRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceMeteorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceMeteor", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceMeteorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceMeteor indicates an expected call of SendLampDeviceMeteor.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceMeteor(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceMeteor", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceMeteor), varargs...)
}

// SendLampDeviceFire mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceFire(ctx context.Context, in *devices_pb.SendLampDeviceFireRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceFireResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceFire", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceFireResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceFire indicates an expected call of SendLampDeviceFire.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceFire(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceFire", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceFire), varargs...)
}

// SendLampDeviceTwinkle mocks base method.
func (m *MockDevicesServiceClient) SendLampDeviceTwinkle(ctx context.Context, in *devices_pb.SendLampDeviceTwinkleRequest, opts ...grpc.CallOption) (*devices_pb.SendLampDeviceTwinkleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendLampDeviceTwinkle", varargs...)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceTwinkleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceTwinkle indicates an expected call of SendLampDeviceTwinkle.
func (mr *MockDevicesServiceClientMockRecorder) SendLampDeviceTwinkle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceTwinkle", reflect.TypeOf((*MockDevicesServiceClient)(nil).SendLampDeviceTwinkle), varargs...)
}

// MockDevicesServiceServer is a mock of DevicesServiceServer interface.
type MockDevicesServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockDevicesServiceServerMockRecorder
}

// MockDevicesServiceServerMockRecorder is the mock recorder for MockDevicesServiceServer.
type MockDevicesServiceServerMockRecorder struct {
	mock *MockDevicesServiceServer
}

// NewMockDevicesServiceServer creates a new mock instance.
func NewMockDevicesServiceServer(ctrl *gomock.Controller) *MockDevicesServiceServer {
	mock := &MockDevicesServiceServer{ctrl: ctrl}
	mock.recorder = &MockDevicesServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevicesServiceServer) EXPECT() *MockDevicesServiceServerMockRecorder {
	return m.recorder
}

// CreateBatCaveDeviceSetting mocks base method.
func (m *MockDevicesServiceServer) CreateBatCaveDeviceSetting(arg0 context.Context, arg1 *devices_pb.CreateBatCaveDeviceSettingRequest) (*devices_pb.CreateBatCaveDeviceSettingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatCaveDeviceSetting", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.CreateBatCaveDeviceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatCaveDeviceSetting indicates an expected call of CreateBatCaveDeviceSetting.
func (mr *MockDevicesServiceServerMockRecorder) CreateBatCaveDeviceSetting(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatCaveDeviceSetting", reflect.TypeOf((*MockDevicesServiceServer)(nil).CreateBatCaveDeviceSetting), arg0, arg1)
}

// GetBatCaveDeviceSetting mocks base method.
func (m *MockDevicesServiceServer) GetBatCaveDeviceSetting(arg0 context.Context, arg1 *devices_pb.GetBatCaveDeviceSettingRequest) (*devices_pb.GetBatCaveDeviceSettingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatCaveDeviceSetting", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.GetBatCaveDeviceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatCaveDeviceSetting indicates an expected call of GetBatCaveDeviceSetting.
func (mr *MockDevicesServiceServerMockRecorder) GetBatCaveDeviceSetting(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatCaveDeviceSetting", reflect.TypeOf((*MockDevicesServiceServer)(nil).GetBatCaveDeviceSetting), arg0, arg1)
}

// UpdateBatCaveDeviceSetting mocks base method.
func (m *MockDevicesServiceServer) UpdateBatCaveDeviceSetting(arg0 context.Context, arg1 *devices_pb.UpdateBatCaveDeviceSettingRequest) (*devices_pb.UpdateBatCaveDeviceSettingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBatCaveDeviceSetting", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.UpdateBatCaveDeviceSettingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBatCaveDeviceSetting indicates an expected call of UpdateBatCaveDeviceSetting.
func (mr *MockDevicesServiceServerMockRecorder) UpdateBatCaveDeviceSetting(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBatCaveDeviceSetting", reflect.TypeOf((*MockDevicesServiceServer)(nil).UpdateBatCaveDeviceSetting), arg0, arg1)
}

// SendLampDeviceOn mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceOn(arg0 context.Context, arg1 *devices_pb.SendLampDeviceOnRequest) (*devices_pb.SendLampDeviceOnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceOn", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceOnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceOn indicates an expected call of SendLampDeviceOn.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceOn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceOn", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceOn), arg0, arg1)
}

// SendLampDeviceOff mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceOff(arg0 context.Context, arg1 *devices_pb.SendLampDeviceOffRequest) (*devices_pb.SendLampDeviceOffResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceOff", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceOffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceOff indicates an expected call of SendLampDeviceOff.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceOff(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceOff", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceOff), arg0, arg1)
}

// SendLampDeviceToggle mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceToggle(arg0 context.Context, arg1 *devices_pb.SendLampDeviceToggleRequest) (*devices_pb.SendLampDeviceToggleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceToggle", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceToggleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceToggle indicates an expected call of SendLampDeviceToggle.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceToggle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceToggle", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceToggle), arg0, arg1)
}

// SendLampDeviceColor mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceColor(arg0 context.Context, arg1 *devices_pb.SendLampDeviceColorRequest) (*devices_pb.SendLampDeviceColorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceColor", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceColorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceColor indicates an expected call of SendLampDeviceColor.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceColor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceColor", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceColor), arg0, arg1)
}

// SendLampDeviceBrightness mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceBrightness(arg0 context.Context, arg1 *devices_pb.SendLampDeviceBrightnessRequest) (*devices_pb.SendLampDeviceBrightnessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceBrightness", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceBrightnessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceBrightness indicates an expected call of SendLampDeviceBrightness.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceBrightness(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceBrightness", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceBrightness), arg0, arg1)
}

// SendLampDeviceAutoBrightnessOn mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceAutoBrightnessOn(arg0 context.Context, arg1 *devices_pb.SendLampDeviceAutoBrightnessOnRequest) (*devices_pb.SendLampDeviceAutoBrightnessOnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceAutoBrightnessOn", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceAutoBrightnessOnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceAutoBrightnessOn indicates an expected call of SendLampDeviceAutoBrightnessOn.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceAutoBrightnessOn(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceAutoBrightnessOn", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceAutoBrightnessOn), arg0, arg1)
}

// SendLampDeviceAutoBrightnessOff mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceAutoBrightnessOff(arg0 context.Context, arg1 *devices_pb.SendLampDeviceAutoBrightnessOffRequest) (*devices_pb.SendLampDeviceAutoBrightnessOffResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceAutoBrightnessOff", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceAutoBrightnessOffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceAutoBrightnessOff indicates an expected call of SendLampDeviceAutoBrightnessOff.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceAutoBrightnessOff(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceAutoBrightnessOff", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceAutoBrightnessOff), arg0, arg1)
}

// SendLampDeviceAutoBrightnessToggle mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceAutoBrightnessToggle(arg0 context.Context, arg1 *devices_pb.SendLampDeviceAutoBrightnessToggleRequest) (*devices_pb.SendLampDeviceAutoBrightnessToggleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceAutoBrightnessToggle", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceAutoBrightnessToggleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceAutoBrightnessToggle indicates an expected call of SendLampDeviceAutoBrightnessToggle.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceAutoBrightnessToggle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceAutoBrightnessToggle", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceAutoBrightnessToggle), arg0, arg1)
}

// SendLampDevicePulse mocks base method.
func (m *MockDevicesServiceServer) SendLampDevicePulse(arg0 context.Context, arg1 *devices_pb.SendLampDevicePulseRequest) (*devices_pb.SendLampDevicePulseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDevicePulse", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDevicePulseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDevicePulse indicates an expected call of SendLampDevicePulse.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDevicePulse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDevicePulse", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDevicePulse), arg0, arg1)
}

// SendLampDeviceMeteor mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceMeteor(arg0 context.Context, arg1 *devices_pb.SendLampDeviceMeteorRequest) (*devices_pb.SendLampDeviceMeteorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceMeteor", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceMeteorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceMeteor indicates an expected call of SendLampDeviceMeteor.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceMeteor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceMeteor", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceMeteor), arg0, arg1)
}

// SendLampDeviceFire mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceFire(arg0 context.Context, arg1 *devices_pb.SendLampDeviceFireRequest) (*devices_pb.SendLampDeviceFireResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceFire", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceFireResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceFire indicates an expected call of SendLampDeviceFire.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceFire(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceFire", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceFire), arg0, arg1)
}

// SendLampDeviceTwinkle mocks base method.
func (m *MockDevicesServiceServer) SendLampDeviceTwinkle(arg0 context.Context, arg1 *devices_pb.SendLampDeviceTwinkleRequest) (*devices_pb.SendLampDeviceTwinkleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLampDeviceTwinkle", arg0, arg1)
	ret0, _ := ret[0].(*devices_pb.SendLampDeviceTwinkleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendLampDeviceTwinkle indicates an expected call of SendLampDeviceTwinkle.
func (mr *MockDevicesServiceServerMockRecorder) SendLampDeviceTwinkle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLampDeviceTwinkle", reflect.TypeOf((*MockDevicesServiceServer)(nil).SendLampDeviceTwinkle), arg0, arg1)
}

// mustEmbedUnimplementedDevicesServiceServer mocks base method.
func (m *MockDevicesServiceServer) mustEmbedUnimplementedDevicesServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedDevicesServiceServer")
}

// mustEmbedUnimplementedDevicesServiceServer indicates an expected call of mustEmbedUnimplementedDevicesServiceServer.
func (mr *MockDevicesServiceServerMockRecorder) mustEmbedUnimplementedDevicesServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedDevicesServiceServer", reflect.TypeOf((*MockDevicesServiceServer)(nil).mustEmbedUnimplementedDevicesServiceServer))
}
