// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/pb/users/users_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	users_pb "github.com/io-1/kuiper/pkg/pb/users"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockUsersServiceClient is a mock of UsersServiceClient interface.
type MockUsersServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockUsersServiceClientMockRecorder
}

// MockUsersServiceClientMockRecorder is the mock recorder for MockUsersServiceClient.
type MockUsersServiceClientMockRecorder struct {
	mock *MockUsersServiceClient
}

// NewMockUsersServiceClient creates a new mock instance.
func NewMockUsersServiceClient(ctrl *gomock.Controller) *MockUsersServiceClient {
	mock := &MockUsersServiceClient{ctrl: ctrl}
	mock.recorder = &MockUsersServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersServiceClient) EXPECT() *MockUsersServiceClientMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUsersServiceClient) CreateUser(ctx context.Context, in *users_pb.CreateUserRequest, opts ...grpc.CallOption) (*users_pb.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateUser", varargs...)
	ret0, _ := ret[0].(*users_pb.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsersServiceClientMockRecorder) CreateUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsersServiceClient)(nil).CreateUser), varargs...)
}

// GetUser mocks base method.
func (m *MockUsersServiceClient) GetUser(ctx context.Context, in *users_pb.GetUserRequest, opts ...grpc.CallOption) (*users_pb.GetUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUser", varargs...)
	ret0, _ := ret[0].(*users_pb.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUsersServiceClientMockRecorder) GetUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUsersServiceClient)(nil).GetUser), varargs...)
}

// GetUserByUsername mocks base method.
func (m *MockUsersServiceClient) GetUserByUsername(ctx context.Context, in *users_pb.GetUserByUsernameRequest, opts ...grpc.CallOption) (*users_pb.GetUserByUsernameResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserByUsername", varargs...)
	ret0, _ := ret[0].(*users_pb.GetUserByUsernameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUsersServiceClientMockRecorder) GetUserByUsername(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUsersServiceClient)(nil).GetUserByUsername), varargs...)
}

// UpdateUser mocks base method.
func (m *MockUsersServiceClient) UpdateUser(ctx context.Context, in *users_pb.UpdateUserRequest, opts ...grpc.CallOption) (*users_pb.UpdateUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUser", varargs...)
	ret0, _ := ret[0].(*users_pb.UpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsersServiceClientMockRecorder) UpdateUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsersServiceClient)(nil).UpdateUser), varargs...)
}

// DeleteUser mocks base method.
func (m *MockUsersServiceClient) DeleteUser(ctx context.Context, in *users_pb.DeleteUserRequest, opts ...grpc.CallOption) (*users_pb.DeleteUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteUser", varargs...)
	ret0, _ := ret[0].(*users_pb.DeleteUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsersServiceClientMockRecorder) DeleteUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsersServiceClient)(nil).DeleteUser), varargs...)
}

// MockUsersServiceServer is a mock of UsersServiceServer interface.
type MockUsersServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUsersServiceServerMockRecorder
}

// MockUsersServiceServerMockRecorder is the mock recorder for MockUsersServiceServer.
type MockUsersServiceServerMockRecorder struct {
	mock *MockUsersServiceServer
}

// NewMockUsersServiceServer creates a new mock instance.
func NewMockUsersServiceServer(ctrl *gomock.Controller) *MockUsersServiceServer {
	mock := &MockUsersServiceServer{ctrl: ctrl}
	mock.recorder = &MockUsersServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersServiceServer) EXPECT() *MockUsersServiceServerMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUsersServiceServer) CreateUser(arg0 context.Context, arg1 *users_pb.CreateUserRequest) (*users_pb.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*users_pb.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsersServiceServerMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsersServiceServer)(nil).CreateUser), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockUsersServiceServer) GetUser(arg0 context.Context, arg1 *users_pb.GetUserRequest) (*users_pb.GetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*users_pb.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUsersServiceServerMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUsersServiceServer)(nil).GetUser), arg0, arg1)
}

// GetUserByUsername mocks base method.
func (m *MockUsersServiceServer) GetUserByUsername(arg0 context.Context, arg1 *users_pb.GetUserByUsernameRequest) (*users_pb.GetUserByUsernameResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*users_pb.GetUserByUsernameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUsersServiceServerMockRecorder) GetUserByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUsersServiceServer)(nil).GetUserByUsername), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockUsersServiceServer) UpdateUser(arg0 context.Context, arg1 *users_pb.UpdateUserRequest) (*users_pb.UpdateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(*users_pb.UpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsersServiceServerMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsersServiceServer)(nil).UpdateUser), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockUsersServiceServer) DeleteUser(arg0 context.Context, arg1 *users_pb.DeleteUserRequest) (*users_pb.DeleteUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(*users_pb.DeleteUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsersServiceServerMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsersServiceServer)(nil).DeleteUser), arg0, arg1)
}

// mustEmbedUnimplementedUsersServiceServer mocks base method.
func (m *MockUsersServiceServer) mustEmbedUnimplementedUsersServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedUsersServiceServer")
}

// mustEmbedUnimplementedUsersServiceServer indicates an expected call of mustEmbedUnimplementedUsersServiceServer.
func (mr *MockUsersServiceServerMockRecorder) mustEmbedUnimplementedUsersServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedUsersServiceServer", reflect.TypeOf((*MockUsersServiceServer)(nil).mustEmbedUnimplementedUsersServiceServer))
}
