// Code generated by MockGen. DO NOT EDIT.
// Source: persistence.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	persistence "github.com/io-1/kuiper/internal/interactions/persistence"
	reflect "reflect"
)

// MockPersistence is a mock of Persistence interface.
type MockPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceMockRecorder
}

// MockPersistenceMockRecorder is the mock recorder for MockPersistence.
type MockPersistenceMockRecorder struct {
	mock *MockPersistence
}

// NewMockPersistence creates a new mock instance.
func NewMockPersistence(ctrl *gomock.Controller) *MockPersistence {
	mock := &MockPersistence{ctrl: ctrl}
	mock.recorder = &MockPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistence) EXPECT() *MockPersistenceMockRecorder {
	return m.recorder
}

// CreateInteraction mocks base method.
func (m *MockPersistence) CreateInteraction(interaction persistence.Interaction) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInteraction", interaction)
	ret0, _ := ret[0].(int64)
	return ret0
}

// CreateInteraction indicates an expected call of CreateInteraction.
func (mr *MockPersistenceMockRecorder) CreateInteraction(interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInteraction", reflect.TypeOf((*MockPersistence)(nil).CreateInteraction), interaction)
}

// GetInteraction mocks base method.
func (m *MockPersistence) GetInteraction(id string) (bool, persistence.Interaction) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInteraction", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(persistence.Interaction)
	return ret0, ret1
}

// GetInteraction indicates an expected call of GetInteraction.
func (mr *MockPersistenceMockRecorder) GetInteraction(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInteraction", reflect.TypeOf((*MockPersistence)(nil).GetInteraction), id)
}

// GetInteractionDetails mocks base method.
func (m *MockPersistence) GetInteractionDetails(id string) ([]persistence.InteractionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInteractionDetails", id)
	ret0, _ := ret[0].([]persistence.InteractionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInteractionDetails indicates an expected call of GetInteractionDetails.
func (mr *MockPersistenceMockRecorder) GetInteractionDetails(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInteractionDetails", reflect.TypeOf((*MockPersistence)(nil).GetInteractionDetails), id)
}

// UpdateInteraction mocks base method.
func (m *MockPersistence) UpdateInteraction(interaction persistence.Interaction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInteraction", interaction)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInteraction indicates an expected call of UpdateInteraction.
func (mr *MockPersistenceMockRecorder) UpdateInteraction(interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInteraction", reflect.TypeOf((*MockPersistence)(nil).UpdateInteraction), interaction)
}

// DeleteInteraction mocks base method.
func (m *MockPersistence) DeleteInteraction(interaction persistence.Interaction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInteraction", interaction)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInteraction indicates an expected call of DeleteInteraction.
func (mr *MockPersistenceMockRecorder) DeleteInteraction(interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInteraction", reflect.TypeOf((*MockPersistence)(nil).DeleteInteraction), interaction)
}

// CreateKeypadCondition mocks base method.
func (m *MockPersistence) CreateKeypadCondition(keypadCondition persistence.KeypadCondition) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeypadCondition", keypadCondition)
	ret0, _ := ret[0].(int64)
	return ret0
}

// CreateKeypadCondition indicates an expected call of CreateKeypadCondition.
func (mr *MockPersistenceMockRecorder) CreateKeypadCondition(keypadCondition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeypadCondition", reflect.TypeOf((*MockPersistence)(nil).CreateKeypadCondition), keypadCondition)
}

// GetKeypadCondition mocks base method.
func (m *MockPersistence) GetKeypadCondition(id string) (bool, persistence.KeypadCondition) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeypadCondition", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(persistence.KeypadCondition)
	return ret0, ret1
}

// GetKeypadCondition indicates an expected call of GetKeypadCondition.
func (mr *MockPersistenceMockRecorder) GetKeypadCondition(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeypadCondition", reflect.TypeOf((*MockPersistence)(nil).GetKeypadCondition), id)
}

// GetKeypadConditionByMac mocks base method.
func (m *MockPersistence) GetKeypadConditionByMac(mac string) (bool, persistence.KeypadCondition) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeypadConditionByMac", mac)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(persistence.KeypadCondition)
	return ret0, ret1
}

// GetKeypadConditionByMac indicates an expected call of GetKeypadConditionByMac.
func (mr *MockPersistenceMockRecorder) GetKeypadConditionByMac(mac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeypadConditionByMac", reflect.TypeOf((*MockPersistence)(nil).GetKeypadConditionByMac), mac)
}

// GetKeypadConditionByMacAndButtonID mocks base method.
func (m *MockPersistence) GetKeypadConditionByMacAndButtonID(mac string, buttonID int) (bool, persistence.KeypadCondition) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeypadConditionByMacAndButtonID", mac, buttonID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(persistence.KeypadCondition)
	return ret0, ret1
}

// GetKeypadConditionByMacAndButtonID indicates an expected call of GetKeypadConditionByMacAndButtonID.
func (mr *MockPersistenceMockRecorder) GetKeypadConditionByMacAndButtonID(mac, buttonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeypadConditionByMacAndButtonID", reflect.TypeOf((*MockPersistence)(nil).GetKeypadConditionByMacAndButtonID), mac, buttonID)
}

// UpdateKeypadCondition mocks base method.
func (m *MockPersistence) UpdateKeypadCondition(keypadCondition persistence.KeypadCondition) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeypadCondition", keypadCondition)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeypadCondition indicates an expected call of UpdateKeypadCondition.
func (mr *MockPersistenceMockRecorder) UpdateKeypadCondition(keypadCondition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeypadCondition", reflect.TypeOf((*MockPersistence)(nil).UpdateKeypadCondition), keypadCondition)
}

// DeleteKeypadCondition mocks base method.
func (m *MockPersistence) DeleteKeypadCondition(keypadCondition persistence.KeypadCondition) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeypadCondition", keypadCondition)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKeypadCondition indicates an expected call of DeleteKeypadCondition.
func (mr *MockPersistenceMockRecorder) DeleteKeypadCondition(keypadCondition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeypadCondition", reflect.TypeOf((*MockPersistence)(nil).DeleteKeypadCondition), keypadCondition)
}

// CreateLampEvent mocks base method.
func (m *MockPersistence) CreateLampEvent(keypadCondition persistence.LampEvent) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLampEvent", keypadCondition)
	ret0, _ := ret[0].(int64)
	return ret0
}

// CreateLampEvent indicates an expected call of CreateLampEvent.
func (mr *MockPersistenceMockRecorder) CreateLampEvent(keypadCondition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLampEvent", reflect.TypeOf((*MockPersistence)(nil).CreateLampEvent), keypadCondition)
}

// GetLampEvent mocks base method.
func (m *MockPersistence) GetLampEvent(id string) (bool, persistence.LampEvent) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLampEvent", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(persistence.LampEvent)
	return ret0, ret1
}

// GetLampEvent indicates an expected call of GetLampEvent.
func (mr *MockPersistenceMockRecorder) GetLampEvent(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLampEvent", reflect.TypeOf((*MockPersistence)(nil).GetLampEvent), id)
}

// GetLampEventsByKeypadConditionID mocks base method.
func (m *MockPersistence) GetLampEventsByKeypadConditionID(id string) ([]persistence.LampEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLampEventsByKeypadConditionID", id)
	ret0, _ := ret[0].([]persistence.LampEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLampEventsByKeypadConditionID indicates an expected call of GetLampEventsByKeypadConditionID.
func (mr *MockPersistenceMockRecorder) GetLampEventsByKeypadConditionID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLampEventsByKeypadConditionID", reflect.TypeOf((*MockPersistence)(nil).GetLampEventsByKeypadConditionID), id)
}

// UpdateLampEvent mocks base method.
func (m *MockPersistence) UpdateLampEvent(lampEvent persistence.LampEvent) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLampEvent", lampEvent)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLampEvent indicates an expected call of UpdateLampEvent.
func (mr *MockPersistenceMockRecorder) UpdateLampEvent(lampEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLampEvent", reflect.TypeOf((*MockPersistence)(nil).UpdateLampEvent), lampEvent)
}

// DeleteLampEvent mocks base method.
func (m *MockPersistence) DeleteLampEvent(lampEvent persistence.LampEvent) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLampEvent", lampEvent)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLampEvent indicates an expected call of DeleteLampEvent.
func (mr *MockPersistenceMockRecorder) DeleteLampEvent(lampEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLampEvent", reflect.TypeOf((*MockPersistence)(nil).DeleteLampEvent), lampEvent)
}

// CreateConditionsToEvents mocks base method.
func (m *MockPersistence) CreateConditionsToEvents(conditionsToEvents persistence.ConditionsToEvents) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConditionsToEvents", conditionsToEvents)
	ret0, _ := ret[0].(int64)
	return ret0
}

// CreateConditionsToEvents indicates an expected call of CreateConditionsToEvents.
func (mr *MockPersistenceMockRecorder) CreateConditionsToEvents(conditionsToEvents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConditionsToEvents", reflect.TypeOf((*MockPersistence)(nil).CreateConditionsToEvents), conditionsToEvents)
}

// GetConditionsToEvents mocks base method.
func (m *MockPersistence) GetConditionsToEvents(id string) (bool, persistence.ConditionsToEvents) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConditionsToEvents", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(persistence.ConditionsToEvents)
	return ret0, ret1
}

// GetConditionsToEvents indicates an expected call of GetConditionsToEvents.
func (mr *MockPersistenceMockRecorder) GetConditionsToEvents(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConditionsToEvents", reflect.TypeOf((*MockPersistence)(nil).GetConditionsToEvents), id)
}

// UpdateConditionsToEvents mocks base method.
func (m *MockPersistence) UpdateConditionsToEvents(conditionsToEvents persistence.ConditionsToEvents) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConditionsToEvents", conditionsToEvents)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConditionsToEvents indicates an expected call of UpdateConditionsToEvents.
func (mr *MockPersistenceMockRecorder) UpdateConditionsToEvents(conditionsToEvents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConditionsToEvents", reflect.TypeOf((*MockPersistence)(nil).UpdateConditionsToEvents), conditionsToEvents)
}

// DeleteConditionsToEvents mocks base method.
func (m *MockPersistence) DeleteConditionsToEvents(conditionsToEvents persistence.ConditionsToEvents) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConditionsToEvents", conditionsToEvents)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConditionsToEvents indicates an expected call of DeleteConditionsToEvents.
func (mr *MockPersistenceMockRecorder) DeleteConditionsToEvents(conditionsToEvents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConditionsToEvents", reflect.TypeOf((*MockPersistence)(nil).DeleteConditionsToEvents), conditionsToEvents)
}
