// Code generated by MockGen. DO NOT EDIT.
// Source: persistence.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	persistence "github.com/io-1/kuiper/internal/interactions/persistence"
	reflect "reflect"
)

// MockPersistence is a mock of Persistence interface.
type MockPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceMockRecorder
}

// MockPersistenceMockRecorder is the mock recorder for MockPersistence.
type MockPersistenceMockRecorder struct {
	mock *MockPersistence
}

// NewMockPersistence creates a new mock instance.
func NewMockPersistence(ctrl *gomock.Controller) *MockPersistence {
	mock := &MockPersistence{ctrl: ctrl}
	mock.recorder = &MockPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistence) EXPECT() *MockPersistenceMockRecorder {
	return m.recorder
}

// CreateInteraction mocks base method.
func (m *MockPersistence) CreateInteraction(interaction persistence.Interaction) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInteraction", interaction)
	ret0, _ := ret[0].(int64)
	return ret0
}

// CreateInteraction indicates an expected call of CreateInteraction.
func (mr *MockPersistenceMockRecorder) CreateInteraction(interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInteraction", reflect.TypeOf((*MockPersistence)(nil).CreateInteraction), interaction)
}

// GetInteraction mocks base method.
func (m *MockPersistence) GetInteraction(id string) (bool, persistence.Interaction) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInteraction", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(persistence.Interaction)
	return ret0, ret1
}

// GetInteraction indicates an expected call of GetInteraction.
func (mr *MockPersistenceMockRecorder) GetInteraction(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInteraction", reflect.TypeOf((*MockPersistence)(nil).GetInteraction), id)
}

// UpdateInteraction mocks base method.
func (m *MockPersistence) UpdateInteraction(interaction persistence.Interaction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInteraction", interaction)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInteraction indicates an expected call of UpdateInteraction.
func (mr *MockPersistenceMockRecorder) UpdateInteraction(interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInteraction", reflect.TypeOf((*MockPersistence)(nil).UpdateInteraction), interaction)
}

// DeleteInteraction mocks base method.
func (m *MockPersistence) DeleteInteraction(interaction persistence.Interaction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInteraction", interaction)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInteraction indicates an expected call of DeleteInteraction.
func (mr *MockPersistenceMockRecorder) DeleteInteraction(interaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInteraction", reflect.TypeOf((*MockPersistence)(nil).DeleteInteraction), interaction)
}
