// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package interactions_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InteractionsServiceClient is the client API for InteractionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionsServiceClient interface {
	CreateInteraction(ctx context.Context, in *CreateInteractionRequest, opts ...grpc.CallOption) (*CreateInteractionResponse, error)
	GetInteraction(ctx context.Context, in *GetInteractionRequest, opts ...grpc.CallOption) (*GetInteractionResponse, error)
	UpdateInteraction(ctx context.Context, in *UpdateInteractionRequest, opts ...grpc.CallOption) (*UpdateInteractionResponse, error)
	DeleteInteraction(ctx context.Context, in *DeleteInteractionRequest, opts ...grpc.CallOption) (*DeleteInteractionResponse, error)
}

type interactionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionsServiceClient(cc grpc.ClientConnInterface) InteractionsServiceClient {
	return &interactionsServiceClient{cc}
}

func (c *interactionsServiceClient) CreateInteraction(ctx context.Context, in *CreateInteractionRequest, opts ...grpc.CallOption) (*CreateInteractionResponse, error) {
	out := new(CreateInteractionResponse)
	err := c.cc.Invoke(ctx, "/interactions_pb.InteractionsService/CreateInteraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) GetInteraction(ctx context.Context, in *GetInteractionRequest, opts ...grpc.CallOption) (*GetInteractionResponse, error) {
	out := new(GetInteractionResponse)
	err := c.cc.Invoke(ctx, "/interactions_pb.InteractionsService/GetInteraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) UpdateInteraction(ctx context.Context, in *UpdateInteractionRequest, opts ...grpc.CallOption) (*UpdateInteractionResponse, error) {
	out := new(UpdateInteractionResponse)
	err := c.cc.Invoke(ctx, "/interactions_pb.InteractionsService/UpdateInteraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsServiceClient) DeleteInteraction(ctx context.Context, in *DeleteInteractionRequest, opts ...grpc.CallOption) (*DeleteInteractionResponse, error) {
	out := new(DeleteInteractionResponse)
	err := c.cc.Invoke(ctx, "/interactions_pb.InteractionsService/DeleteInteraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionsServiceServer is the server API for InteractionsService service.
// All implementations must embed UnimplementedInteractionsServiceServer
// for forward compatibility
type InteractionsServiceServer interface {
	CreateInteraction(context.Context, *CreateInteractionRequest) (*CreateInteractionResponse, error)
	GetInteraction(context.Context, *GetInteractionRequest) (*GetInteractionResponse, error)
	UpdateInteraction(context.Context, *UpdateInteractionRequest) (*UpdateInteractionResponse, error)
	DeleteInteraction(context.Context, *DeleteInteractionRequest) (*DeleteInteractionResponse, error)
	mustEmbedUnimplementedInteractionsServiceServer()
}

// UnimplementedInteractionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInteractionsServiceServer struct {
}

func (*UnimplementedInteractionsServiceServer) CreateInteraction(context.Context, *CreateInteractionRequest) (*CreateInteractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInteraction not implemented")
}
func (*UnimplementedInteractionsServiceServer) GetInteraction(context.Context, *GetInteractionRequest) (*GetInteractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInteraction not implemented")
}
func (*UnimplementedInteractionsServiceServer) UpdateInteraction(context.Context, *UpdateInteractionRequest) (*UpdateInteractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInteraction not implemented")
}
func (*UnimplementedInteractionsServiceServer) DeleteInteraction(context.Context, *DeleteInteractionRequest) (*DeleteInteractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInteraction not implemented")
}
func (*UnimplementedInteractionsServiceServer) mustEmbedUnimplementedInteractionsServiceServer() {}

func RegisterInteractionsServiceServer(s *grpc.Server, srv InteractionsServiceServer) {
	s.RegisterService(&_InteractionsService_serviceDesc, srv)
}

func _InteractionsService_CreateInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).CreateInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interactions_pb.InteractionsService/CreateInteraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).CreateInteraction(ctx, req.(*CreateInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_GetInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).GetInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interactions_pb.InteractionsService/GetInteraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).GetInteraction(ctx, req.(*GetInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_UpdateInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).UpdateInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interactions_pb.InteractionsService/UpdateInteraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).UpdateInteraction(ctx, req.(*UpdateInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionsService_DeleteInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServiceServer).DeleteInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interactions_pb.InteractionsService/DeleteInteraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServiceServer).DeleteInteraction(ctx, req.(*DeleteInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InteractionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interactions_pb.InteractionsService",
	HandlerType: (*InteractionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInteraction",
			Handler:    _InteractionsService_CreateInteraction_Handler,
		},
		{
			MethodName: "GetInteraction",
			Handler:    _InteractionsService_GetInteraction_Handler,
		},
		{
			MethodName: "UpdateInteraction",
			Handler:    _InteractionsService_UpdateInteraction_Handler,
		},
		{
			MethodName: "DeleteInteraction",
			Handler:    _InteractionsService_DeleteInteraction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/interactions/interactions.proto",
}
